### ISSUE TITLE
Setup Travis for ci

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/plugins#10]
@jlooper you can either add travis to the repo or if you could adjust my permission to admin, I can setup travis ci. This will help with the frontend unit tests we will be using here to keep sanity amongst contributions.

**Comment by jlooper** [comment]
I've changed all 3 folks' access to level Admin :)

**Comment by NathanWalker** [comment]
Thank you, I'll set this up!

**Comment by georgeedwards** [comment]
I've turned on the builds! NB: it's failing. Maybe @NathanWalker could take a look?
