### ISSUE TITLE
[datetimepicker] iOS 14 compatibility?

### ISSUE THREAD

**Issue by relez** [NativeScript/plugins#11]
I am trying to make it work on iOS 14 (NS 7+Angular 10) and this is how it looks like:
<img width="414" alt="Greenshot 2020-09-18 09 44 24" src="https://user-images.githubusercontent.com/3420851/93612992-42421f00-f99e-11ea-8ec3-ce5b059cf5c7.png">

**Comment by NathanWalker** [comment]
We assume this is dateimepicker- in future if can mention that in your description or title :) - thanks for heads up, we'll have a look this week.

**Comment by mreall** [comment]
@NathanWalker it looks like a PR is available to fix this issue. Is someone able to review it and publish the update? Thanks for helping.
