### ISSUE TITLE
[@nativescript/detox] Wrong path for android apk

### ISSUE THREAD

**Issue by mmeven** [NativeScript/plugins#110]
Hello,

I've been trying to use detox for e2e testing on Android.

Trying to start the tests (with detox test -c android) throws the following error : 
```
'/Users/myusername/dev/native-white/platforms/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk' could not be found, did you run './gradlew assembleAndroidTest'?
```

even though the .detoxc.json contains the following path : 
```  ...
    "android": {
      "binaryPath": "platforms/android/app/build/outputs/apk/debug/app-debug.apk"
   ...
```

Am I missing something ?

Thanks in advance

**Comment by keerl** [comment]
Could you attach your project? I can take a look at it.

**Comment by mmeven** [comment]
Thanks @keerl 

I can't attach the whole project, but I reproduced it in a blank app attached. I just created an app with ns create, choosing the angular template. I then followed the steps from the @nativescript/detox README and tried to run the tests, nothing more.

[detoxApkIssue.zip](https://github.com/NativeScript/plugins/files/6206388/detoxApkIssue.zip)

**Comment by keerl** [comment]
Did you add the NativeScript Detox plugin to the project? It isn't in the attached project. If not, add it with `ns plugin add @nativescript/detox`. Once I added that and changed the `minSdkVersion` in `App_Resources/Android/app.gradle` to 18 it worked just fine. Your `.detoxrc.json` is different than the one in the README, but it still seems to be working.

**Comment by mmeven** [comment]
I honestly don't know how I missed those two. Thank you for your time !
