### ISSUE TITLE
[@nativescript/geolocation] ImagePicker dependency somehow ended up on the 7.1.0 version on npm 

### ISSUE THREAD

**Issue by 13dante04** [NativeScript/plugins#114]
I checked the package.json on github from @nativescript/geolocation which hasn't got the @nativescript/imagepicker dependency, Bu somehow the version that's on npm
(you can check it out here: https://www.npmjs.com/package/@nativescript/geolocation?activeTab=dependencies) has it and it crashes my build with the same issue mentioned in #89 related to @natvescript/camera. I resolved the issue by downgrading @nativescript/geolocation to 7.0.0.

The issue that stops the build process appears on android at API level 29 and above. I think it's also related to #41.

package.json dependencies from https://registry.npmjs.org/@nativescript/geolocation/-/geolocation-7.1.0.tgz:

```
  "dependencies": {
    "nativescript-permissions": "~1.3.0",
    "@nativescript/imagepicker": "1.0.3"
  },
```

**Comment by NathanWalker** [comment]
Very strange indeed - Looking to publish a 7.1.1 shortly with this resolved.

**Comment by NathanWalker** [comment]
7.1.1 published now - lemme know if still issue and we can reopen this if needed.
