### ISSUE TITLE
[@nativescript/geolocation]  Accuracy is not defined on Utils

### ISSUE THREAD

**Issue by jan-medina** [NativeScript/plugins#115]
When trying to use geolocation according to the instructions, I get the following error.

Property 'Accuracy' does not exist on type '{ GC: () => any; RESOURCE_PREFIX: string; FILE_PREFIX: string; isFontIconURI: (uri: string) => boolean; isDataURI: (uri: string) => boolean; isFileOrResourcePath: (path: string) => boolean; ... 33 more ...; verifyCallback: (value: any) => void; }'.ts(2339)

Am I doing something wrong?

**Comment by NathanWalker** [comment]
@jan-medina when you can, could you share your package.json? Curious what versions you may be using.

**Comment by jan-medina** [comment]
@NathanWalker  Sure! This is the file.
> {
  "name": "@nativescript/template-blank-ng",
  "main": "src/main.ts",
  "displayName": "Blank",
  "templateType": "App template",
  "version": "8.0.4",
  "description": "NativeScript Application",
  "author": "NativeScript Team <oss@nativescript.org>",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "files": [
    "App_Resources",
    "hooks",
    "src",
    "tools",
    "!tools/assets",
    ".editorconfig",
    "references.d.ts",
    "tsconfig.json"
  ],
  "keywords": [
    "nstudio",
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "tns",
    "template",
    "category-general"
  ],
  "repository": "<fill-your-repository-here>",
  "homepage": "https://github.com/NativeScript/nativescript-app-templates",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "dependencies": {
    "@angular/animations": "~11.2.7",
    "@angular/common": "~11.2.7",
    "@angular/compiler": "~11.2.7",
    "@angular/core": "~11.2.7",
    "@angular/forms": "~11.2.7",
    "@angular/platform-browser": "~11.2.7",
    "@angular/platform-browser-dynamic": "~11.2.7",
    "@angular/router": "~11.2.7",
    "@nativescript-community/ui-mapbox": "^6.2.8",
    "@nativescript/angular": "~11.8.0",
    "@nativescript/core": "~8.0.0",
    "@nativescript/geolocation": "^7.1.1",
    "@nativescript/theme": "~3.0.1",
    "reflect-metadata": "~0.1.13",
    "rxjs": "^6.6.7",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.2.7",
    "@nativescript/android": "8.0.0",
    "@nativescript/types": "~8.0.0",
    "@nativescript/webpack": "beta",
    "@ngtools/webpack": "~11.2.6",
    "typescript": "^4.0.7"
  },
  "private": "true",
  "readme": "NativeScript Application"
}

**Comment by NathanWalker** [comment]
Hmm interesting - is that stack from your code or plugin? do you have the full stack?

**Comment by jan-medina** [comment]
It is from my code. In fact, I was following the instructions on the nativescript webpage.

**Comment by NathanWalker** [comment]
Make sure using:
```
import { Enums } from '@nativescript/core'; // Enums is deprecated in {N} 8 and will be removed in 9

Enums.Accuracy...

// so you can also use this which is exact same thing if using {N} 8
import { CoreTypes } from '@nativescript/core';

CoreTypes.Accuracy....
```

For more context here the move to `CoreTypes` is for the eventually planning to split *UI* types out of core to make all {N} libraries more flexible for broader use cases so likely `UITypes` would be introduced in the future to further distill usages and clarity.

**Comment by jan-medina** [comment]
Thank you! It works

**Comment by andrew-mykhalchuk** [comment]
Might be a good idea to add this change to plugins readme: https://github.com/NativeScript/plugins/blob/main/packages/geolocation/README.md
