### ISSUE TITLE
[@nativescript/google-pay] Does not appear to be deployed correctly.

### ISSUE THREAD

**Issue by jcassidyav** [NativeScript/plugins#116]
When I do a ```ns plugin add @nativescript/google-pay``` all I get in the node_modules/@nativescript/google-pay directory is a package.json.

Is this an oversight or is the package not ready for use?

**Comment by NathanWalker** [comment]
@jcassidyav we just bumped a 0.1.1 out there - could you `ns clean` and confirm with that?

**Comment by jcassidyav** [comment]
@NathanWalker yep 0.1.1 installs fine, thanks for getting it sorted so quickly.
