### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/plugins#12]
We have to decide a database...

A couple choices;
1. A SQL Database; the data we do use and need in this project is very structured and does fit nicely inside SQL tables.  We can use postgresql, or mysql.   I lean toward pgsql; just because it can do everything and way more...  :+1: 
2. NoSQL Database, because it is hip.   I don't think this site really fits the NoSQL model; but there is nothing stopping us from storing structured data in a NoSQL database...
3. JSON files; they are easily parsed by everything, and easily generated.   Our data needs are not that great...
1. A List of plugins and all data relating to the plugin.
2. A List of Users
3. A List of User, linked to a Plugin ratings

**Comment by NathanWalker** [comment]
Postgresql has my vote. As long as you can provide a nice api to work with it.

Otherwise json files would work fine as far as the frontend is concerned.

**Comment by georgeedwards** [comment]
I quite like noSQL (probs. MongoDB), again - I agree that it is probably not the most appropriate for our site, but it gives future flexibility if we want to widen the scope of the project. 
As it's part of the whole MEAN thing, it should be pretty well known by our user base. 
Also, I think MongoDB has good guides and a low barrier to entry for future contributors. and the [Mongoose ODM](http://mongoosejs.com/) gives you some nice structure and makes it easier to expose clean APIs.

But I don't feel massively strongly about this.

**Comment by jlooper** [comment]
I agree with George, MongoDB is de facto for our JS-oriented community so we would be better able to get help to develop it and maintain it down the road. Easy setup wtih Modulus.

**Comment by NathanaelA** [comment]
If we are using noSQL then there is no point in even using Mongo...  Just leave it as plain JSON files.  Mongo doesn't add anything to the mix but another moving piece that can break.  We don't have enough data that using a full noSQL system makes any sense..     If we want to actually use a Database rather than NoSQL, then I would say use a read database, PgSQL has my vote; but I'm not opposed to MySQL if others would rather use it..

MySQL is more known in the industry than Mongo; PgSQL less so, but PgSQL is very very nice and has the capability to do not only noSQL stuff; but the ability to do realtime notifications on ANY data changed...

**Comment by NathanWalker** [comment]
We use PgSQL + Angular with [Infowrap](https://infowrap.com) 👍  I'm a big fan. +1

It's actually better than the MEAN stack imo.

**Comment by roblav96** [comment]
https://www.rethinkdb.com/ for the win
