### ISSUE TITLE
[@nativescript/google-pay] successful payment token payment parsing

### ISSUE THREAD

**Issue by jcassidyav** [NativeScript/plugins#120]
Currently the plugin tries to parse the token data into it's constituent parts, protocolVersion etc.

However from my reading of:
https://developers.google.com/pay/api/web/reference/response-objects#PaymentMethodTokenizationData

There are no guarantees of the format of the token when the type is PAYMENT_GATEWAY, for example when you set the gateway to 'example' in the request you just get back a string "examplePaymentMethodToken".

I believe that the token string should be returned without parsing when the type is PAYMENT_GATEWAY, or perhaps an attempt to parse made but always return the raw token.

Currently setting the gateway to example will crash an app because it fails to parse the token to an object.

e.g. cardpoint expects the full token to be forwarded to them:  https://developer.cardpointe.com/guides/google-pay#cardSecure-request-parameters

**Comment by NathanWalker** [comment]
Published in 0.1.2
