### ISSUE TITLE
Starting May 5th, you must let us know why your app requires broad storage access

### ISSUE THREAD

**Issue by asharghi** [NativeScript/plugins#124]
I got a message from Play Store saying that I can't update my app from May 5th if I still use `requestLegacyExternalStorage`

<img width="946" alt="Screenshot 2021-05-01 at 20 34 55" src="https://user-images.githubusercontent.com/9407896/116791818-199a1000-aabd-11eb-9550-b54cddcce69f.png">

`android:requestLegacyExternalStorage="true"` is required(?) by the camera and imagepicker plugin (my app uses the image picker).

The "Learn more" button links to: https://support.google.com/googleplay/android-developer/answer/10467955

How can we solve this?

**Comment by mayerlench** [comment]
I was wondering the same thing. Does it mean this plugin needs to be updated?

**Comment by triniwiz** [comment]
You can test this by using the `alpha` tag for `@nativescript/core` and `@nativescript/imagepicker`

**Comment by asharghi** [comment]
Imagepicker works for me on
"@nativescript/core": "^8.0.5-alpha.0",
"@nativescript/imagepicker": "^1.0.4-alpha.0",

**Comment by NathanWalker** [comment]
We'll publish final versions on Friday or Monday, we want to verify few other things regarding this but feel free to use the alpha's mentioned above for anyone that comes across this.

**Comment by jcassidyav** [comment]
Does this fix then introduce a dependency on NS 8 if using the to be released version of imagepicker?

**Comment by SergeyMell** [comment]
I've tested the image picker with alpha versions of the plugin and core. It works well if to render it as an Image. However, I failed to get a file in order to upload it to firebase storage for example. I've tried multiple options i.e.
```
asset: ImageAsset // <= <file received from the plugin after selection>;

const file = File.fromPath(asset.android); // code just hangs on this line
```
or
```
asset: ImageAsset // <= <file received from the plugin after selection>;

const res = await ImageSource.fromAsset(asset);
const knownPath = knownFolders.temp();
const folderPath = path.join(knownPath.path, "CosmosDataBank");
const p = path.join(folderPath, "Test.png");
const saved = res.saveToFile(p, "png");  // code just hangs on this line
```
Am I doing smth wrong or additional changes should be done on the side of `core` and `plugin`?

**Comment by triniwiz** [comment]
So with the latest change it’s just using the uri passed from the image if you logged .android you would see something like content:// you can also use that to get an inputstream or file-descriptor which you can use to upload, we were thinking about adding some utils to make things like this easier

**Comment by SergeyMell** [comment]
Thanks a lot for your answer.
Are you going to update `@nativescript/camera` plugin also? Since for now it seems that it doesn't work even with alpha versions of core and imagepicker.

I'm getting
```
JS: asset
JS: {
JS:   "_observers": {},
JS:   "_options": {
JS:     "width": 787.5,
JS:     "height": 787.5,
JS:     "keepAspectRatio": true
JS:   },
JS:   "_android": "/storage/emulated/0/Android/data/com.repmove.app/files/NSIMG_20210509_22713.jpg"
JS: }
```
and error when trying to read it

**Comment by triniwiz** [comment]
I’ll look into the camera also

**Comment by SergeyMell** [comment]
Thank you!
I would be very glad if you answer one more question (the last one). Could you advise some file picker plugin that allows selecting an arbitrary file of any extension (actually I need xlsx but it doesn't matter) for some custom processing? Recently I was using `nativescript-mediafilepicker` but now it is affected with the same issue of scoped storage.

**Comment by triniwiz** [comment]
Nothing comes to mind atm but hopefully they update it soon

**Comment by tujlaky** [comment]
Is there any update on the camera plugin?
