### ISSUE TITLE
Plugin issues, here or main package?

### ISSUE THREAD

**Issue by chimmelb** [NativeScript/plugins#13]
Looking at @nativescript/background-http, and there is a section for NS7 stating: "Source managed here", being a link to this repo, `NativeScript/plugins`

There is an issue we have also ran into, https://github.com/NativeScript/nativescript-background-http/issues/270 (caught us off-guard for iOS 14, breaks our app)

Should issues be posted here since that is where source code is managed, or is the existing issue at the right place?

**Comment by NathanWalker** [comment]
Post here yep 👍

**Comment by mreall** [comment]
@NathanWalker, do we need to create another issue or are the details mentioned in the ticket @chimmelb references sufficient?

**Comment by benediktveith** [comment]
Any updates here ?

**Comment by brysem** [comment]
> Any updates here ?

This issue has been solved by https://github.com/NativeScript/plugins/pull/16
