### ISSUE TITLE
Google analytics ID

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/plugins#13]
@jlooper one last thing with registered services. I created a segment.io account for this project to use using this login (only authorized users can see this):
https://www.infowrap.com/2316/notes

If you could setup a google analytics project for this and let me know the tracking ID.

**Comment by rdlauer** [comment]
Status of this? We should have everything we need here, correct?

**Comment by georgeedwards** [comment]
@NathanWalker I can;t remember if you got around to filling this in?
