### ISSUE TITLE
Cannot run demos

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/plugins#131]
I'm looking to create a PR and wanted to run the demos first. Followed the steps to setup the single repo. But whenever I try to run the vanilla demos on either iOS or android I'm getting the following error:
```
Cannot find module '@nativescript/localize/hooks/before-watchPatterns.js'
Require stack:
- /Users/peter/Projects/nativescript-plugins/apps/demo/hooks/before-watchPatterns/nativescript-localize.js
- /usr/local/lib/node_modules/nativescript/lib/common/services/hooks-service.js
- /usr/local/lib/node_modules/nativescript/lib/common/yok.js
- /usr/local/lib/node_modules/nativescript/lib/bootstrap.js
- /usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js
- /usr/local/lib/node_modules/nativescript/bin/tns
ERROR: Something went wrong in @nrwl/run-commands - Command failed: ns debug android --no-hmr --env.testing
The script called "apps.demo.android" which runs "nx run demo:android" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
```

Tried with isolate as well, but still no go.

**Comment by NathanWalker** [comment]
@PeterStaev thanks for the help. The localize plugin is only plugin in workspace that contains 'hooks' and thus has to be built first before running the demos. You can `npm start` > `localize` (this will narrow down menu to `@nativescript.localize.build`) and then hit 'enter'.  You can now run the demo's (I'll make a note about this in readme).

**Comment by PeterStaev** [comment]
@NathanWalker , I have already run the `build all` command. But I just tried building `localize` and I still get the same error.

**Comment by NathanWalker** [comment]
@PeterStaev let's hop on a zoom in next couple days to look together - Does your demo package.json contain reference to `../packages/etc.` or `../dist/packages/etc.`? For localize only it should reference `../dist/packages/localize`

**Comment by PeterStaev** [comment]
I have what you have set up in the repo 😉  I have not made ANY changes. 
https://github.com/NativeScript/plugins/blob/88cdcb2675af374a85e780bf3e2b2d1f610e139e/apps/demo/package.json#L7-L32

**Comment by PeterStaev** [comment]
Ok, I performed a full clean and full rebuild again and this time it worked! Not sure what messed up the first time I did this...
