### ISSUE TITLE
[@nativescript/directions] Google Maps opens and does not load the route

### ISSUE THREAD

**Issue by jamescodesthings** [NativeScript/plugins#135]
# Overview 
When opening Google Maps using the plugin, if google maps is not already open it will hang showing the expected destination.

This appears to be intermittent, if you switch back to your app and tap your button again Google Maps loads the route.

Have noticed the issue on iOS and need to retest on android.

# Suggested Fix
Updating the URL in the plugin to use the [Universal URL](https://developers.google.com/maps/documentation/urls/get-started#directions-action) opens maps with the route loaded first time as expected.

This is iOS 9.0+, so should not impede compatibility.

Will knock up a fix and get a PR up tomorrow.

**Comment by asharghi** [comment]
It also loads if you tap on another traveling type (walking or driving) and back to the original traveling type. It works fine on Apple Maps if the device doesn't have Google Maps installed.
