### ISSUE TITLE
native-script-social-share not compatible with nativescript 8

### ISSUE THREAD

**Issue by nicmanzini** [NativeScript/plugins#137]
**ERROR in ./node_modules/nativescript-social-share/social-share.android.js 4:15-51
Module not found: Error: Can't resolve 'tns-core-modules/platform' in '/Users/iomedia/ns-v7-bov/node_modules/nativescript-social-share'**

> using description file: /Users/iomedia/ns-v7-bov/node_modules/nativescript-social-share/package.json (relative path: .)
    resolve as module
      looking for modules in /Users/iomedia/ns-v7-bov/node_modules
        /Users/iomedia/ns-v7-bov/node_modules/**tns-core-modules doesn't exist**
      /Users/iomedia/ns-v7-bov/node_modules/**nativescript-social-share/node_modules doesn't exist or is not a directory**
      /Users/iomedia/ns-v7-bov/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/iomedia/ns-v7-bov/node_modules
        /Users/iomedia/ns-v7-bov/node_modules/**tns-core-modules doesn't exist**
      looking for modules in /Users/iomedia/node_modules
        /Users/iomedia/node_modules/tns-core-modules doesn't exist
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

**Comment by triniwiz** [comment]
You need `@nativescript/social-share`
