### ISSUE TITLE
Front End Framework

### ISSUE THREAD

**Issue by georgeedwards** [NativeScript/plugins#14]
So the UI of the site will be based on Nina's wireframe's as discussed on Slack. First thing's first, @jlooper  are those based on a Telerik Front-end Library?

If so, we need to arrange a license (if required) for that. Then I can integrate that libaray. 

If not, then we will likely need to choose one (Bootstrap, Materialize, Kendo UI etc.), or build everything from scratch. I'll wait to hear from Jen/Nina before discussing this further.

**Comment by NathanWalker** [comment]
My vote here would be: https://github.com/ng-bootstrap/ng-bootstrap

They are incredibly well architected and fast (for instance hit this site:  https://ng-bootstrap.github.io/#/components/accordion on mobile [jump around to diff components] - performs really well even under pressure), plus the modal implementation is best I've ever seen with Angular2, and we will probably need to use a modal or 2 on the site, almost always need to somewhere.

**Comment by georgeedwards** [comment]
Yes, 👍 

However, I want to hear if Nina's work was based on anything specific, otherwise I like bootstrap too!

**Comment by NathanWalker** [comment]
@georgeedwards I have ng-bootstrap integrated which is agnostic to many implementations. Feel free to begin developments on any issues you'd like to take on including mocking data to start some initial grid display views similar to concepts.

If we need to pivot on a frontend framework, I can help execute that.

**Comment by georgeedwards** [comment]
@NathanWalker Awesome! Yes I saw. Am waiting for feedback from Telerik on your email and then I will press ahead.
