### ISSUE TITLE
Grid Display

### ISSUE THREAD

**Issue by georgeedwards** [NativeScript/plugins#15]
As noted on Nina's wireframes, core to the whole site will be the grid view for the plugins. Here is Nina's current proposal, although there are a number of tweaks that have been discussed:

[![enter image description here][1]][1]

A sensible place to start I expect will be to build this out with some mock data. Once there is an answer on #14 then I will start this and agree with @NathanWalker and @NathanaelA what data structure we need. 

  [1]: https://i.stack.imgur.com/Tvn26.png

**Comment by NathanWalker** [comment]
@georgeedwards great idea to build some mock data for this to get some wiring going.
Feel free to build a structure that works for you and a grid display; we can tweak with real format later. Will help get some things off ground. 👍

**Comment by georgeedwards** [comment]
Awesome, I'll make a start and then invite comments! Just waiting for the #14 response
