### ISSUE TITLE
[@nativescript/geolocation] App waiting for response until timeout on Android, after execute geolocation.enableLocationRequest() and allow location permission

### ISSUE THREAD

**Issue by YutangShi** [NativeScript/plugins#161]
Hi, I have an issue on my Android App.

When I execute `geolocation.enableLocationRequest()` App will be pop up a window to require permission. if I click allow location permission than  App will be wait for response until to timeout.

is anyone have same issue?

```
function onPageLoaded(args) {
    try {
        page = args.object;
        page.actionBarHidden = true;
        
        geolocation.isEnabled().then(value => {
            if (!value) {
                console.log("NO permissions!");
                geolocation.enableLocationRequest()
            } else {
                console.log("Have location permissions");
            }
        })
    } catch(e) {
        console.log(e)
    }
}

```

Device: Pixel 4
Android Version: 11

**Comment by siewedu** [comment]
Hi YutangShi,

if you want your code to react on the result of the permission request you have to listen to the promise which is returned by `geolocation.enableLocationRequest()`. So just try this:
`geolocation.enableLocationRequest().then(() => console.log("permission was granted"), () => console.log("permission was denied"))`

**Comment by YutangShi** [comment]
@siewedu thank you for your advice.

Finally, I found the problem. I didn't do this part, so i can't get permission.

```
android {  
  // other stuff here

  project.ext {
    googlePlayServicesVersion = "16.+"
  }
}
```

I will be close this issue.
