### ISSUE TITLE
[nativescript/geolocation] Android bundle upload checks ACCESS_BACKGROUND_LOCATION

### ISSUE THREAD

**Issue by oliverqn** [NativeScript/plugins#164]
I recently integrated this plugin into my app to check the current user location on user behalf (user actively presses a button for fetching the location). No `geolocation.watchLocation(...)` has been added, I just use ` geolocation.getCurrentLocation(...)`. When building my app and uploading the aab to the PlayStore it told me that the app permission changes for ACCESS_BACKGROUND_LOCATION.

I haven't added this permission in AndroidManifest.xml nor do I plan to use this feature. I just use ACCESS_COARSE_LOCATION and ACCESS_FINE_LOCATION for fetching current user location.

Could you please give me a tipp on how I can get rid of this message when uploading the bundle?

**Comment by NathanWalker** [comment]
Hi @oliverqn we’ll look at removing that in next patch and just noting in README - however you can clear it right now by doing this:

1. npm pack @nativescript/geolocation

This will create a .tgz file.
Double click to unpack and navigate in the ‘package’.

2. open the platforms/android/AndroidManifest.xml
And remove this line:
https://github.com/NativeScript/plugins/blob/65846a30d08d27a463b6b3f3a818a7a3be32a3a2/packages/geolocation/platforms/android/AndroidManifest.xml#L4

3. Then “npm pack” from inside the “package” folder. This will create another .tgz file. Drag it to the root of your project and switch your package.json to use it:

“@nativescript/geolocation”: “file:nativescript-geolocation-7.2.1.tgz”

4. then clean your project: “ns clean”

5. now build and upload to store.

**Comment by oliverqn** [comment]
That's great! I will try it and close this ticket if working. 

Thank you for the quick reply on this 🥇

**Comment by oliverqn** [comment]
Your suggested workaround/solution works, thx for your help 👍

**Comment by SingleMalted** [comment]
@oliverqn @NathanWalker The workaround is good as a temp. solution but we should keep this ticket open until this issue is patched.

Thanks

**Comment by mykone** [comment]
Yes please. How soon can we resolve this issue without the hack?

**Comment by chimmelb** [comment]
Just noting that this temp fix worked for me as well. Thank you for the good instructions. 
My app v1.3.2 on Aug 2 was fine, and with no AndroidManifest.xml changes the Sept 9 version was rejected.  Google not taking ACCESS_BACKGROUND_LOCATION lightly, and flags it as sensitive (in web console, Policy -> App Content -> Sensitive App Permissions). Denied my release with it included, since not the main feature/purpose of the app.

**Comment by bradmartin** [comment]
8.0.0 published with the breaking change, see README for what permissions to add to your app.
