### ISSUE TITLE
Angulartics2 Stops the app from running

### ISSUE THREAD

**Issue by georgeedwards** [NativeScript/plugins#17]
Building and running the app currently works, but the app won't run. The client console reads:

> Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:5555/node_modules/angulartics2/index.js Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:61 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/angulartics2/index.js(…) "Report this error at https://github.com/NativeScript/plugins/issues"(anonymous function) @ localhost/:61
http://localhost:5555/node_modules/angulartics2/src/providers/angulartics2-segment.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:5555/node_modules/angulartics2/index.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:5555/node_modules/angulartics2/src/providers/angulartics2-segment.js Failed to load resource: the server responded with a status of 404 (Not Found)

Looks like a systemJS issue. e.g. `http://localhost:5555/node_modules/angulartics2/index.js` should be `http://localhost:5555/node_modules/angulartics2/dist/index.js`

**Comment by georgeedwards** [comment]
Sounds like this is caused by the most recent patch release of angulartics.

**Comment by NathanWalker** [comment]
@georgeedwards I have just updated the repo to latest upstream parent changes which fixes this issue as well. 

Please do the following on your local master branch when you get back in front of this:
```
git stash // if you had any local changes
git pull
rm -rf node_modules
npm i
git stash pop  // to drop your changes back in if you had any
```

Then you should be all set. 👍

**Comment by bradmartin** [comment]
Wish I knew git this well :)
