### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by georgeedwards** [NativeScript/plugins#18]
I am working on the homepage of Nina's proposal. I think it should be split up such that there is:

- [x] Plugin Display (toggles between grid and lines)
- [x] Plugin Display Service for managing sorting, filtering and associated API interactions
- [x] Search Component

- [ ] Sidebar

**Search Component:** This should be pretty straight forward, but do we want to support auto-complete / suggestions? I suppose this is more of a backend question, as this is pretty easy to do on the front-end. If we do, it would be nice to do an Observable based implementation as per the [Wikipedia](https://angular.io/docs/ts/latest/guide/server-communication.html#!#cors) based example in the angular docs.

**Plugin Display Component:** I will basically implement this as per Nina's wireframe. I'll start with the grid layout and then build out the toggling to line view. 

**Sidebar Component:** OK, here it would be really useful to get a consensus. What `Categories` would we like to support, also what `Sort By` options do we want (Name, Date Added, Downloads, Quality - is this possible in v1)? 

**Plugin Display Service:** This should call the backend API to return paginated data, possibly sorted, possibly excluding some categories. We will need to agree a data format (what to be included and how) for this. We can do this upfront, or start building the front end with mock data and iteratively work out what we need then use that? I prefer the latter, but it should be fairly straight forward, so don't mind strongly either way. 

@NathanaelA I am sure you will have some opinions about search and how we agree data structure.
@NathanWalker I am happy to build out the first two component, do you want to have some input on the service? I am happy to build this, but it strikes me that this might be up your street?

**Comment by georgeedwards** [comment]
Of course we could also call the npm API from the client i.e. `https://registry.npmjs.org/<plugin-name>/latest` that way we would always have up to date version number and descriptions etc. 

Obviously that would potentially get out of sync with any backend testing we are doing, but would reduce server load and the amount of data we are storing. 

@NathanaelA  @NathanWalker Thoughts please :) 

The only bit that the npmJS API doesn't give you is the readme (which is used in Nina's plugin detail view). Is that something we will store on the backend for each plugin (potentially quite a bit of data - do we store images/other repo assets)?

**Comment by NathanaelA** [comment]
@georgeedwards - I actually currently pull all data including readme's for ns.rocks.   Docs are only about 3megs of space.  

On NS.rocks, I was only pulling the data nightly.  However since we are actually getting more plugins, we can up this to every hour.  So there would only be a short window of time data on a plugin could be out dated.

**Comment by georgeedwards** [comment]
@NathanaelA  OK awesome! How do you deal with relative links to static assets in the repo e.g. images?

**Comment by NathanaelA** [comment]
@georgeedwards - No idea; I store the docs but haven't started using them.   I can probably do some regex rewriting of the docs when we start figuring out where to stick stuff.   

Hmm, that does bring up an interesting question; do we want to store the images locally or do we just want to rewrite the URL's to point to the npm/git version?   Thoughts @NathanWalker & @georgeedwards ?

**Comment by georgeedwards** [comment]
OK, My gut feeling would be to store readme's as .md and regex any relative links to absolute references to the source repo.
Then we can render just the text on the front end and use the source repo for assets. This reduces the storage burden and means we don't end up storing other peoples potentially unsafe, potentially large data.

**Comment by georgeedwards** [comment]
Also @NathanaelA Can I rely on `plugin.name` being unique?

**Comment by georgeedwards** [comment]
I am going to ignore the sidebar for the time being...
