### ISSUE TITLE
@nativescript/google-signin Android: GoogleSignIn.configure() not working

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/plugins#194]
I am trying @nativescript/google-signin 1.0.0.alpha.0 together with the new @nativescript/firebase auth functionality and I am not able to use GoogleSignIn:

When I call this:

```
GoogleSignin.configure({
    scopes: [
      "https://www.googleapis.com/auth/contacts.readonly",
      "https://www.googleapis.com/auth/user.birthday.read"
    ]
  });
```

the Promise gets rejected and I just get "Error" in the console. It is hard to find out what exactly is failing.
On iOS, the call is made correctly.

When I remove that scopes options
```
GoogleSignin.configure({});
```
the call is made correctly on Android as well.

When I now try to call `GoogleSignin.signIn()`, it fails with the message:
_java.lang.IllegalArgumentException: can use only lower 16 bits for requestCode_

The general Google configuration to use Google signin on Android should be fine actually, as I was able to use that functionality with the old nativescript-plugin-firebase plugin from Eddy.

Here is a demo app for reproducing this issue if that helps:
[ns-firebase-auth.zip](https://github.com/NativeScript/plugins/files/7467128/ns-firebase-auth.zip)

**Comment by triniwiz** [comment]
Please install using the `@alpha` this was fixed
