### ISSUE TITLE
geolocation plugin exception

### ISSUE THREAD

**Issue by dvlpr91** [NativeScript/plugins#209]
In the catch of 'enableLocationRequest', the reason is not formatted, so it is difficult to handle the exception.

example...
```
if (err == 'Location not enabled.') {
  // ...
} else if (JSON.stringify(err) === foo) {
  // ...
} else ...
```

What should I do?

**Comment by devyaz** [comment]
I am also getting `enable location request first! ` error in {N} 8.1 but I do call the `enablelocationrequest()`, app run fine before upgrading code hasn't changed
