### ISSUE TITLE
API Outline

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/plugins#21]
@georgeedwards @NathanWalker 

Ok, what makes the most sense for you for getting back the data set you are requesting?
Individual requests like (all data comes back in JSON):

- /api/1/getCategories  <---  Returns a list of categories
- /api/1/getAuthors <-- Return list of authors        
- /api/1/getPlugins [/all /category /author] <-- Returns a set of plugins for the group specified
- /api/1/search/(value)

Or do you want something where you just say; 
/api/1/getAllData
   And it returns you a JSON structure with Authors, Categories, and Plugins and you can then link and filter everything together in your nng app?

What is your preference.

**Comment by georgeedwards** [comment]
@NathanaelA Awesome - I personally prefer the 
/api/1/getCategories <--- Returns a list of categories
/api/1/getAuthors <-- Return list of authors
/api/1/getPlugins [/all /category /author] <-- Returns a set of plugins for the group specified
/api/1/search/(value)

option, as it makes for the minimum of data transfer from client/backend. Obviously where `/api/1/getPlugins [/all /category /author]` would be the most useful.

**Comment by NathanaelA** [comment]
Ok, API is UP.   

http://nativescript.rocks:3004/api/getCategories
http://nativescript.rocks:3004/api/getAuthors
http://nativescript.rocks:3004/api/search/(value)
http://nativescript.rocks:3004/api/getPlugin/(id)
http://nativescript.rocks:3004/api/getPlugins [/all /category/(id) /author/(id) ]

Once I have time to setup the Xervo (Modulas) servers, we will move it, so the url will change in the future...  :-)

This is ONLY the global data from NPM.   At this point I still need to do:
- get NPM specific plugin info  (This will give us category, platforms, etc)
- get Readme's per plugin (Readme)
- do a Github data pull / download pull per plugin (Any github specific data)
- add filtering to eliminate invalid plugins that passed the standard "nativescript" test

Any data that is in the set is what NPM provides as a global record when it returns all bazillion npm packages in the entire eco system.

**Comment by NathanaelA** [comment]
We also need to decide what data we want returned in a /getPlugins so that we aren't returning more data than needed.   Right now I have it returning EVERYTHING, but as you decide what to show in the list view; please let me know which fields and we will eliminate the fields that are not needed.

**Comment by NathanWalker** [comment]
The api is really fast, nice work @NathanaelA 👍

**Comment by NathanaelA** [comment]
Ok, the API now has all the data.  Data import system is done for v1 stuff.  ;-)
