### ISSUE TITLE
[@nativescript/facebook] androidx.fragment 1.3.0+ breaks navigation in nested frames

### ISSUE THREAD

**Issue by delaneyb** [NativeScript/plugins#218]
Wasn't sure if this issue was better suited for here or NativeScript/NativeScript:

* A vanilla 8.1.5 / 8.1.1 project created with `ns create` from the main repo defines androidx.fragment version 1.2.5 to be used via [build.gradle](https://github.com/NativeScript/android-runtime/blob/332bf68481b0215c841c8d41e0c877887f07249d/test-app/app/build.gradle#L406). Navigation in nested frames works just fine.
* @nativescript/facebook's gradle file adds a dependency on [facebook-login](https://mvnrepository.com/artifact/com.facebook.android/facebook-login), which in turn depends on facebook-common
* facebook-common, from [version 12](https://mvnrepository.com/artifact/com.facebook.android/facebook-common/12.0.0) now depends on androidx.fragment 1.3.0
* This dependency overrides the default 1.2.5, which breaks navigation in nested frames. My observation was that [transitionOrAnimationCompleted (core/ui/frame/fragment.transitions.android.ts#L653)](https://github.com/NativeScript/NativeScript/blob/17c85107ba84953630b0471c1f6f3d68f6d59f76/packages/core/ui/frame/fragment.transitions.android.ts#L653) was never getting called for the nested frame when its initial content was loaded when androidx.fragment 1.3.0 was used, leading to [_executingContext never being set to null](https://github.com/NativeScript/NativeScript/blob/17c85107ba84953630b0471c1f6f3d68f6d59f76/packages/core/ui/frame/frame-common.ts#L263) so then [processNextNavigationEntry](https://github.com/NativeScript/NativeScript/blob/17c85107ba84953630b0471c1f6f3d68f6d59f76/packages/core/ui/frame/index.android.ts#L167) would return early and not perform the actual navigation when called next time.

Minimal repro - app with nested frame on which navigation does nothing due to override of androidx.fragment version to 1.3.0 via App_Resources/Android/app.gradle: https://github.com/delaneyb/androidx-fragment-130-repro

As a temporary workaround the com.facebook.android:facebook-login version can be downgraded to 11.3.0

Related:
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/pull/1868

**Comment by edusperoni** [comment]
Hey! I ran into this recently and pushed a fix:

https://github.com/NativeScript/NativeScript/pull/9725

Try running with the alpha tag in NativeScript and see if that helps

**Comment by delaneyb** [comment]
> Hey! I ran into this recently and pushed a fix:
> 
> [NativeScript/NativeScript#9725](https://github.com/NativeScript/NativeScript/pull/9725)
> 
> Try running with the alpha tag in NativeScript and see if that helps

Aweeesomee, must have just missed that one! Navigation on a nested frame in the little repro I threw together runs fine with both androidx.fragment 1.3.0 and 1.4.0 with your changes. Need to migrate our main project to NS8 after which I can do some more thorough testing. I'll keep an eye on https://github.com/NativeScript/NativeScript/pull/9728. Thanks Eduardo!
