### ISSUE TITLE
Determine Fields to return on API

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/plugins#22]
We need to decide what fields you want for the getAllPlugins (GAP); right now we are returning a LOT of data including the readmes, and processing log.

GAP should only return what is needed to view the list of plugins, so I need to know from you guys what fields you need so we can limit this down.   

The /GetPlugin/[id] will return everything for the detail page.

**Comment by georgeedwards** [comment]
So we definitely need:

- title

- author

- description

- stars

- android

- ios

- repo

Then anything @NathanWalker needs for search and categories
