### ISSUE TITLE
Configure Progress Servers for API / Processing

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/plugins#23]
Setup the Xervo server(s) for dealing with the processing / API stuff.  

Since we are only doing V1 at this point we don't actually need two servers.  The code will work fine from multiple servers; but no reason to pay for a second server at this point as the processing is fairly quick.

- [x] - Allocate a Xervo server
- [x] - Deploy system
- [x] - Setup MongoDB
- [x] - Convert API & processing to JSON #24 
- [x] - Store & retrieve on startup persistent data in/from MongoDB

**Comment by georgeedwards** [comment]
@NathanaelA  Can this be closed now?

**Comment by NathanaelA** [comment]
No, parts of this has changed.   I've updated the list of things to do...   None of this will effect the frontend team; this is all backend stuff that has changed because it doesn't support pgsql...

**Comment by NathanaelA** [comment]
This has been finished for a couple weeks, and already deployed.
