### ISSUE TITLE
Google Maps Marker

### ISSUE THREAD

**Issue by maddockst** [NativeScript/plugins#233]
Can you please provide an example of how to add a marker to a map? I've tried the following but to no avail, it throws an error:

`Cannot set property 'position' of undefined`

```
onMapReady({ map }) {
    const marker = new Marker();

    marker.position = { lat: 52, lng: -1 };

    map.addMarker(marker);
}
```

**Comment by triniwiz** [comment]
You don’t create a marker , the `addMarker` method takes an object with options  which will be used to create an return a marker.

**Comment by maddockst** [comment]
Do you mean like this?

```
onMapReady({ map }) {
    map.addMarker({
        position: { lat: 52, lng: -1 },
    });
}
```

If so, I get the following error:

`Cannot set property 'map' of undefined`

**Comment by triniwiz** [comment]
Yes like that 
```xml
<MapView ready="onMapReady"/>
```

```ts
onMapReady(event) {
    const marker = event.map.addMarker({
        position: { lat: 52, lng: -1 },
    });
}
```

**Comment by maddockst** [comment]
I've done that, but I get this error:

```
TypeError: Cannot set property 'map' of undefined
```

It appears to be failing here, the `native` property doesn't appear to be present on `marker`: 

```
marker.native.map = this.native;
```

EDIT: Should it not be `marker.map = this.native` as `map` is on the root of a new `GMSMarker`?

**Comment by triniwiz** [comment]
`marker.native` is the native instance `GMSMarker` which has a `map` setter `this.native` should be an instance of the mapview `GMSMapView` but it seems like `marker` is returning null from [here](https://github.com/NativeScript/plugins/blob/2069472088a8450909c62f7164e26e50edb517c7/packages/google-maps/index.ios.ts#L892) which gets the native instance from [here](https://github.com/NativeScript/plugins/blob/2069472088a8450909c62f7164e26e50edb517c7/packages/google-maps/utils/index.ios.ts#L33)

**Comment by maddockst** [comment]
Looking at the function below, it is returning a `GMSMarker`, not `{ native: GSMarker }`

```
export function intoNativeMarkerOptions(options: MarkerOptions) {
  const opts = GMSMarker.new()
  // Code Ommitted
  return opts;
}
```

So if I change it to this it works perfectly:

```
addMarker(options) {
    const marker = intoNativeMarkerOptions(options);
    marker.map = this.native; // Changed from map.native.marker = this.native;
    return marker;
}
```

If I add a console in:

```
addMarker(options) {
    const marker = intoNativeMarkerOptions(options);

    console.log(marker); // ADDED CONSOLE TO PROVE `marker` IS A GMSMarker

    marker.map = this.native;
    return marker;
}
```

The output is a `GMSMarker` not `{ native: GMSMarker }`:

`CONSOLE LOG: <GMSMarker: 0x7f80c9963c20> (null) (52.411504, -1.778907)`

**Comment by triniwiz** [comment]
That's why it's wrapped in a [Marker](https://github.com/NativeScript/plugins/blob/2069472088a8450909c62f7164e26e50edb517c7/packages/google-maps/index.ios.ts#L982) so it we can do `marker.native.map = this.native;`

**Comment by maddockst** [comment]
But surely it should be something like this then?

```
addMarker(options) {
    const marker = Marker.fromNative(intoNativeMarkerOptions(options)); // WRAP IT IN A `MARKER`
    marker.native.map = this.native;
    return marker;
}
```

You're just returning the native `GMSMarker` from `addMarker` instead of the wrapping it with a `Marker` using `Marker.fromNative`

**Comment by triniwiz** [comment]
Which version of the package are you using ?

**Comment by maddockst** [comment]
1.0.0-alpha.0

**Comment by triniwiz** [comment]
You're not using the latest alpha please install using the `@alpha` tag

**Comment by maddockst** [comment]
Ok thanks.

You may want to change the `README.md` as running `ns plugin add @nativescript/google-maps` installs `1.0.0-alpha.0`
