### ISSUE TITLE
[@nativescript/facebook] - LoginResult and AccessToken return empty objects

### ISSUE THREAD

**Issue by agardes** [NativeScript/plugins#237]
Thanks a lot for those awesome plugins. 

I'm using Facebook Plugin and the login process seems to work (from my FB Developer account) but returns both empty objects for `LoginResult` and `AccessToken`. I tried both example provided : 

```
try {
   const result = await LoginManager.logInWithPermissions(['public_profile']); // LoginResult
   const accessToken = AccessToken.currentAccessToken();
   console.log(result)
   console.log(accessToken)
} catch (e) {
   console.log(e)
}
```

and 

```
LoginManager.logInWithPermissions(['public_profile']).then(profile => {
          console.log('profile', profile);
}).catch(e => {
         console.log('Facebook login error:', e);
})
```

Any idea why? Thanks

I'm using : 
"@nativescript/facebook": "^1.0.0-alpha.0",
And 7.1.0 version of Nativescript

EDIT : 
I'm testing with my android phone where Facebook App is installed. 
I should add that using an emulator, without the Facebook App  `result` is not empty anymore

**Comment by triniwiz** [comment]
Install the latest alpha `npm i @nativescript/facebook@alpha` this should contain the fix

**Comment by agardes** [comment]
@triniwiz thanks a lot for your quick answer, it fixed it!
