### ISSUE TITLE
Refactor from PGSQL to JSON Data/Mongo

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/plugins#24]
Change API to store everything in a local JSON DB and use a Memory table for running the api's .  The Processing DB will be stored in Mongo for persistence because resetting an Xervo instances will probably cause us to lose any data generated, and we want to maintain data persistence.

**Comment by georgeedwards** [comment]
@NathanaelA I think this is done now? Can we close?

**Comment by NathanaelA** [comment]
Nope, this is NOT done.   The api is still pulling data from a Postgresql instance on one of my servers.  I plan on working on this probably next week to try and refactor everything from postgresql into a simple json datastore.

**Comment by NathanaelA** [comment]
I should make a note; the FrontEnd API the app calls will NOT change; so this change is really for me to track my progress in swapping the internals from using PGSql to JSON.     So this will have NO impact on the ng2 app.

**Comment by georgeedwards** [comment]
OK cool - was just trying to tidy up some of the old issues, didn't realise this was still active.

**Comment by NathanWalker** [comment]
Sounds like frontend calls will have to change since 3004 port cannot be used for many internal networks - this is high priority at moment.

**Comment by NathanaelA** [comment]
Well technically the url will change; but I "assume" that the url is located in one place in the app; so the change to the frontend should be minimal as all you are doing is changing it from the nativescript.rocks url to plugins.nativescript.... as the same piece that serves the front end will be serving the data too once I am done.  ;-)

**Comment by NathanWalker** [comment]
Yessir, defined it one spot - lemme know when you're getting close and could try it out in dev before we make the next push. Thanks!

**Comment by NathanaelA** [comment]
This has been fixed for a couple weeks now.
