### ISSUE TITLE
Google Maps - UserData

### ISSUE THREAD

**Issue by maddockst** [NativeScript/plugins#243]
@triniwiz I normally use `userData` to hold information which is related to a pin. I've tried to store `userdata` on the marker manually myself but it didn't work, both come back as `undefined` inside the `markerTap` event. I believe it's because you're returning new instances of `Marker` for the `onMarkerTap` event:

```
setupMarkers() {
    const marker = this.map.addMarker({ position: { lat: 1, lng: 1 } });

    (marker as any).userData = { some: 'data' };
    (marker as any).native.userData = { some: 'data' };
}

onMarkerTap({ marker }){
    console.log(marker.userData); // undefined
    console.log(marker.native.userData); // undefined
}
```

Is there a plan to support this or a temporary fix to get this working?

**Comment by stefalda** [comment]
Hi,
 it seems that there is no userData field in this plugin.

I created a Map (JS not Google! ;.-) ) and stored the information this way...

```
 private aziendeMap = new Map<String, any>();
```

I've used the title as key but you could use your coordinates:

```
  const marker = this.map.addMarker();
        marker.position = {
          lat:
            azienda.latitude, lng:
            azienda.longitude
        };

        marker.title = azienda.nome;

        marker.snippet = azienda.indirizzo + "\n" + azienda.cap + azienda.citta;

        this.aziendeMap.set(marker.title, azienda);
        coordinates.push([azienda.latitude, azienda.longitude]);
```


then in the tap event I've accessed the map this way:

```
 onMarkerInfoWindowTapped(args) {
    let azienda = this.aziendeMap.get(args.marker.title);
   ...
```

Hope this helps...

**Comment by maddockst** [comment]
Is there any update on when this will be added?

**Comment by rigor789** [comment]
I don't think anyone is currently looking at implementing something like this, feel free to give it a go if you don't mind getting into the codebase a little bit and explore.

**Comment by triniwiz** [comment]
A quick search shows ios still supports this on their native instance so, we could try using the kotlin ext to add similar support if they always return the same instance
