### ISSUE TITLE
[@nativescript/local-notifications] Notifications don't work on devices with android 12+

### ISSUE THREAD

**Issue by ndt080** [NativeScript/plugins#245]
Notifications don't work on devices with android 12+
 Error: java.lang.IllegalArgumentException:  ... : Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent

**Comment by SingleMalted** [comment]
Right... I had to drop the target to vs 30 to get it working.

**Comment by triniwiz** [comment]
fixed: 6442ef270fdc6d2e85abd73fbd72773a7777e5a6

**Comment by kennethkeim** [comment]
I'm still getting the same issue on version `5.0.4`
