### ISSUE TITLE
ReferenceError: IQKeyboardManager is not defined

### ISSUE THREAD

**Issue by mrzanirato** [NativeScript/plugins#248]
Hello,

I have a problem with IQKeyboardManager NS 8 compiling Android ( iOS works fine )

Thanks in advance

Just after app starts I get this:

ReferenceError: IQKeyboardManager is not defined
System.err: File: (file: src/webpack:/btop/webpack/bootstrap:27:0)
System.err: 
System.err: StackTrace: 
System.err: ./src/app/app.module.ts(file: src/webpack:/btop/src/app/app.module.ts:22:0)
System.err:     at __webpack_require__(file: src/webpack:/btop/webpack/bootstrap:24:0)
System.err:     at fn(file: src/webpack:/btop/webpack/runtime/hot module replacement:61:0)
System.err:     at ./src/main.ts(file:///data/data/com.fabricandum.coromarketing/files/app/bundle.js:14:73)
System.err:     at __webpack_require__(file: src/webpack:/btop/webpack/bootstrap:24:0)
System.err:     at __webpack_exec__(file:///data/data/com.fabricandum.coromarketing/files/app/bundle.js:7484:39)
System.err:     at (file:///data/data/com.fabricandum.coromarketing/files/app/bundle.js:7485:189)
System.err:     at __webpack_require__.X(file: src/webpack:/btop/webpack/runtime/startup entrypoint:6:0)
System.err:     at (file:///data/data/com.fabricandum.coromarketing/files/app/bundle.js:7485:47)
System.err:     at (file:///data/data/com.fabricandum.coromarketing/files/app/bundle.js:7490:3)
System.err:     at require(:1:266)

**Comment by NathanWalker** [comment]
Hi @mrzanirato check that your package.json contains ` "@nativescript/iqkeyboardmanager": "^2.0.0",` and then make sure you are not accessing `IQKeyboardManager` without a platform conditional since that symbol is only available on iOS, for example:
```
if (isIOS) {
   const manager = IQKeyboardManager....
}
```

**Comment by mrzanirato** [comment]
@NathanWalker thanks! I had forgotten isIOS ...
