### ISSUE TITLE
Truncate or wrap long descriptions

### ISSUE THREAD

**Issue by jlooper** [NativeScript/plugins#25]
Since the cards seem to need to be the same height, we may need to have to truncate very long descriptions.

<img width="300" alt="screenshot 2017-01-16 15 19 00" src="https://cloud.githubusercontent.com/assets/1450004/21999379/d6d16ae4-dc07-11e6-84e4-5f3860aa75d7.png">

**Comment by georgeedwards** [comment]
Should be better now? https://github.com/NativeScript/plugins/commit/334be1087f07ae19adc8c1ecbcdf15d0fed3d7be
