### ISSUE TITLE
[background-http]

### ISSUE THREAD

**Issue by JakeAi** [NativeScript/plugins#251]
When using the newest version of background-http. I am getting this error.
`java.lang.IllegalArgumentException: You have to set defaultNotificationChannel in your Application subclass`
```
/vendor.js:4113:17) in createMultiPart(
/vendor.js in multipartUpload at line 4092:21
```

**Comment by triniwiz** [comment]
Please check out the [updated docs](https://docs.nativescript.org/plugins/background-http.html#usage)

**Comment by jamescodesthings** [comment]
For anyone who lands here like I did after updating from 5.x to 6.x.

The `Call init before the app starts to initialize the http background service` was the area that was a little unclear in the docs.

I needed to add a call to the plugin's `init` method in my `main.ts` file to fix this:
```ts
// ...
import { init } from '@nativescript/background-http';

// Init background-http service (required here for droid).
init();

// ...
runNativeScriptAngularApp({
  appModuleBootstrap: () => platformNativeScript().bootstrapModule(AppModule),
});
```
