### ISSUE TITLE
nativescript/camera not working on Android phones

### ISSUE THREAD

**Issue by Adamok258** [NativeScript/plugins#252]
Hi, we experience problems with our Android application that uses nativescript camera (this does not affect iOS). We don't have detailed info but this wasn't happening before, it has started just couple of days/weeks before and it seems to affect almost all Android versions, we could replicate it on 9, 10, 11 and 12. Basically when user tries to open camera app it crashes and displays error message to user before opening.

We are using nativescript/camera 5.0.10.

```
"dependencies": {
    "@angular/animations": "^12.2.5",
    "@angular/common": "^12.2.5",
    "@angular/compiler": "^12.2.5",
    "@angular/core": "^12.2.5",
    "@angular/forms": "^12.2.5",
    "@angular/platform-browser": "^12.2.5",
    "@angular/platform-browser-dynamic": "^12.2.5",
    "@angular/router": "^12.2.5",
    "@nativescript/angular": "^12.2.0",
    "@nativescript/background-http": "^5.0.1",
    "@nativescript/camera": "^5.0.10",
    "@nativescript/core": "^8.1.5",
    "@nativescript/geolocation": "^7.1.1",
    "@nativescript/local-notifications": "^5.1.0",
    "@nativescript/theme": "~3.0.0",
    "@ngx-translate/core": "^13.0.0",
    "@nstudio/nativescript-loading-indicator": "^4.1.2",
    "moment": "^2.29.1",
    "nativescript-clipboard": "^2.0.0",
    "nativescript-permissions": "^1.3.12",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~7.3.0",
    "zone.js": "~0.11.1"
  },
```
This is the code that takes care of asking for permission and taking the picture, which crashes on Android and displays the error message in the bottom part of the code:
```
this.cameraService.requestPermissions()
            .pipe(
                tap(() => {
                    timeModule.setTimeout(() => {
                        this.takingPhoto = true;
                        this.onPhotoInProgressChanged.emit(true);
                    }, 1000);
                }),
                flatMap(() => this.cameraService.takePhoto(this.stepName)),
                tap(() => {
                    this.takingPhoto = false;
                })
            )
            .subscribe((photoWithThumbnail: PhotoWithThumbnail) => {
                this.takenPhoto = photoWithThumbnail;
                if (this.stepItemTypes) {
                    if (this.chosenItemType) {
                        this.onPhotoInProgressChanged.emit(false);
                        this.onPhotoTaken.emit(photoWithThumbnail);
                    }
                } else {
                    this.onPhotoInProgressChanged.emit(false);
                    this.onPhotoTaken.emit(photoWithThumbnail);
                }
            }, error => {
                this.takingPhoto = false;
                this.onPhotoInProgressChanged.emit(false);
                if (error.message === 'cancelled') {
                    return;
                }
                if (error.message === 'widePhotoTaken') {
                    this.handleWidePhotoTakenError();
                    return;
                }
                this.errorHandlingService.handle('Error taking photo', error, 'selfInspection.error.camera', true);
            });
```
Thank you in advance for any help/recommendation.

**Comment by ethan-humphries** [comment]
I'm also experiencing this, it's really sad how many packages are now either broken or no longer maintained since moving to NS8+

Error:

Error Error: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/[redacted]/files/NSIMG_20220408_14528.jpg

This is running on a real device, seems weird to me that it would have emulated in the path

**Comment by NathanWalker** [comment]
Hi @Adamok258 and @ethan-humphries, when either of you get a chance, please run the following and post your results:
```
echo 'y' | npx nativescript-envinfo
```

We use this plugin broadly without issue - it's possible your envinfo info may reveal more pointers we could provide in your cases.

**Comment by NathanWalker** [comment]
`5.0.11` contains an addition that should help your case. If using @nativescript/camera `~5.0.0`, you can `ns clean` and you should then have the addition on your next run.
Let us know if any further issue.

**Comment by ethan-humphries** [comment]
Thankyou!

**Comment by jamescodesthings** [comment]
I had the same error on Android 12 with plugin version 5.0.11. Adding a root path to the paths.xml fixed it.

## Fix That worked for me
Add this `FileProvider` definition to your Application in `App_Resources/Android/src/main/AndroidManifest.xml`:
```xml
<application ...> 
 <!-- Replace com.yourdomain below with your app's bundle ID. -->
 <!-- You can usually find it in nativescript.config.ts/js -->
        <provider
          android:name="androidx.core.content.FileProvider"
          android:authorities="com.yourdomain.provider"
          android:grantUriPermissions="true"
          android:exported="false">
          <meta-data
            tools:replace="android:resource"
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/app_provider_paths" />
        </provider>
</application>
```

Then, create `App_Resources/Android/src/main/res/xml/app_provider_paths.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <root-path
    name="root"
    path="." />
  <external-path
    name="external"
    path="."/>
  <external-files-path
    name="external_files"
    path="." />
  <cache-path
    name="cache"
    path="." />
  <external-cache-path
    name="external_cache"
    path="." />
  <files-path
    name="files"
    path="." />
</paths>
```

This replaces the `provider_paths.xml` definitions from `@nativescript/camera` with the definitions in `App_Resources/Android/src/main/res/xml/app_provider_paths.xml`. The definition that fixed this issue for me was the `root-path` definition above.

Request that the root path definition also be added to the plugin. Will PR at some point.

**Comment by jamescodesthings** [comment]
PR Up: https://github.com/NativeScript/plugins/pull/263
