### ISSUE TITLE
failed to build plugin nativescript-phone on Android

### ISSUE THREAD

**Issue by r0nneberg** [NativeScript/plugins#256]
I'm trying to build our NativeScript app to run on my Android Studio Emulator but I keep running into this certain build error:

> > Failed to build plugin nativescript-phone : 
> Error: spawn ./gradlew ENOENT
> Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.IOException: Input/output error
>         at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:62)
>         at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
>         at org.gradle.util.internal.DisconnectableInputStream$1.run(DisconnectableInputStream.java:127)
>         at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: java.io.IOException: Input/output error
>         at java.base/java.io.FileInputStream.readBytes(Native Method)
>         at java.base/java.io.FileInputStream.read(FileInputStream.java:279)
>         at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
>         at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
>         at org.gradle.util.internal.DisconnectableInputStream$1.run(DisconnectableInputStream.java:98)
> 

I already tried to reinstall NativeScript, deleted my node_modules, deleted Android Studio. I've tried to delete nativescript-phone from my package.json-file, ran ns clean, ran tns debug android again but it is still not working. 

my package.json: 

> {
>   "nativescript": {
>     "id": "com.maxtoolbox.vrsta",
>     "tns-android": {
>       "version": "6.2.0"
>     },
>     "tns-ios": {
>       "version": "6.5.2"
>     }
>   },
>   "description": "NativeScript Application",
>   "license": "SEE LICENSE IN <your-license-filename>",
>   "repository": "<fill-your-repository-here>",
>   "dependencies": {
>     "@angular/animations": "~8.2.0",
>     "@angular/common": "~8.2.0",
>     "@angular/compiler": "~8.2.0",
>     "@angular/core": "~8.2.0",
>     "@angular/forms": "~8.2.0",
>     "@angular/platform-browser": "~8.2.0",
>     "@angular/platform-browser-dynamic": "~8.2.0",
>     "@angular/router": "~8.2.0",
>     "@nativescript/theme": "~2.2.0",
>     "html-entities": "^2.3.2",
>     "lodash": "^4.17.21",
>     "moment": "^2.29.1",
>     "nativescript-angular": "~8.20.0",
>     "nativescript-app-sync": "^1.0.7",
>     "nativescript-background-http": "^4.2.1",
>     "nativescript-camera": "^4.5.0",
>     "nativescript-datetimepicker": "^1.2.2",
>     "nativescript-email": "^1.5.5",
>     "nativescript-exit": "^1.0.1",
>     "nativescript-exoplayer": "^4.0.2",
>     "nativescript-feedback": "^1.5.0",
>     "nativescript-fingerprint-auth": "^7.0.2",
>     "nativescript-iqkeyboardmanager": "^1.5.1",
>     "nativescript-pdf-view": "^2.1.0",
>     "nativescript-permissions": "^1.3.8",
>     "nativescript-phone": "^1.4.1",
>     "nativescript-plugin-firebase": "^10.3.0",
>     "nativescript-plugin-statusbar": "^1.0.19",
>     "nativescript-purchase": "^2.0.13",
>     "nativescript-simple-filepicker": "^1.0.2",
>     "nativescript-socket.io": "^0.11.1",
>     "nativescript-ui-sidedrawer": "^8.0.0",
>     "nativescript-videoplayer": "^4.2.1",
>     "nativescript-webview-interface": "^1.4.3",
>     "reflect-metadata": "~0.1.12",
>     "rxjs": "^6.4.0",
>     "tns-core-modules": "~6.2.0",
>     "zone.js": "~0.9.1"
>   },
>   "devDependencies": {
>     "@angular/compiler-cli": "~8.2.0",
>     "@ngtools/webpack": "~8.2.0",
>     "nativescript-dev-webpack": "~1.3.0",
>     "tns-android": "6.2.0",
>     "tns-ios": "6.5.3",
>     "typescript": "~3.5.3"
>   },
>   "gitHead": "a6fec076a20f898feabb4466a2c411158c18a100",
>   "readme": "NativeScript Application"
> }

tns doctor says that everything looks fine.

**Comment by rigor789** [comment]
Run

```bash
echo 'y' | npx nativescript-envinfo
```

And paste the results here.

**Comment by r0nneberg** [comment]
> 

thanks for your reply @rigor789 here are the results: 

> 
```yaml
OS: macOS 12.2.1
CPU: (10) arm64 Apple M1 Max
Shell: /bin/zsh
node: 17.7.1
npm: 8.5.2
nativescript: 8.2.2

# android
java: 11.0.14.1
ndk: Not Found
apis: 25, 26, 27, 28, 29, 30
build_tools: 29.0.0, 30.0.0, 30.0.3
system_images: 
  - android-30 | Google APIs ARM 64 v8a

# ios
xcode: 13.3/13E113
cocoapods: 1.11.3
python: 2.7.18
python3: 3.8.9
ruby: 2.7.5
platforms: 
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~8.2.0",
  "@angular/common": "~8.2.0",
  "@angular/compiler": "~8.2.0",
  "@angular/core": "~8.2.0",
  "@angular/forms": "~8.2.0",
  "@angular/platform-browser": "~8.2.0",
  "@angular/platform-browser-dynamic": "~8.2.0",
  "@angular/router": "~8.2.0",
  "@nativescript/theme": "~2.2.0",
  "html-entities": "^2.3.2",
  "lodash": "^4.17.21",
  "moment": "^2.29.1",
  "nativescript-angular": "~8.20.0",
  "nativescript-app-sync": "^1.0.7",
  "nativescript-background-http": "^4.2.1",
  "nativescript-camera": "^4.5.0",
  "nativescript-datetimepicker": "^1.2.2",
  "nativescript-email": "^1.5.5",
  "nativescript-exit": "^1.0.1",
  "nativescript-exoplayer": "^4.0.2",
  "nativescript-feedback": "^1.5.0",
  "nativescript-fingerprint-auth": "^7.0.2",
  "nativescript-iqkeyboardmanager": "^1.5.1",
  "nativescript-pdf-view": "^2.1.0",
  "nativescript-permissions": "^1.3.8",
  "nativescript-phone": "^1.4.1",
  "nativescript-plugin-firebase": "^10.3.0",
  "nativescript-plugin-statusbar": "^1.0.19",
  "nativescript-purchase": "^2.0.13",
  "nativescript-simple-filepicker": "^1.0.2",
  "nativescript-socket.io": "^0.11.1",
  "nativescript-ui-sidedrawer": "^8.0.0",
  "nativescript-videoplayer": "^4.2.1",
  "nativescript-webview-interface": "^1.4.3",
  "reflect-metadata": "~0.1.12",
  "rxjs": "^6.4.0",
  "tns-core-modules": "~6.2.0",
  "zone.js": "~0.9.1"
},
"devDependencies": {
  "@angular/compiler-cli": "~8.2.0",
  "@ngtools/webpack": "~8.2.0",
  "nativescript-dev-webpack": "~1.3.0",
  "tns-android": "6.2.0",
  "tns-ios": "6.5.3",
  "typescript": "~3.5.3"
}
```

**Comment by r0nneberg** [comment]
I fixed the issue by upgrading to the latest NativeScript version 8.2.3
