### ISSUE TITLE
Plugins build gradle issue

### ISSUE THREAD

**Issue by Mahmoud-64** [NativeScript/plugins#258]
FAILURE: Build failed with an exception.

* Where:
Build file '/home/labs/Desktop/a/NewRepo/Ebhath/Ebhath_Mobile/6/test/mix5/Ebhath_Mobile/platforms/tempPlugin/geolocation/build.gradle' line: 143

* What went wrong:
A problem occurred evaluating root project 'geolocation'.
`> Could not find method compile() for arguments [com.google.android.gms:play-services-location:11.4.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

**Comment by triniwiz** [comment]
You can either upgrade to the latest geolocation plugin or switch the `compile` syntax from that plugin's include gradle to `implementation`

**Comment by Mahmoud-64** [comment]
@triniwiz It worked. thank you for your response
