### ISSUE TITLE
Google Maps userData empty

### ISSUE THREAD

**Issue by maddockst** [NativeScript/plugins#260]
Hi,

I've tried to use the new `userData` property when creating a marker.

However, every time I console the value it's undefined. Am I doing something wrong?

Thanks!

Tom

<img width="495" alt="Screen Shot 2022-04-08 at 17 20 03" src="https://user-images.githubusercontent.com/14302328/162482307-c433c82e-709d-4e62-b072-f9e8b628a175.png">

<img width="406" alt="Screen Shot 2022-04-08 at 17 20 18" src="https://user-images.githubusercontent.com/14302328/162482336-adfc0b91-80b4-46f9-b7d4-bf30dbed90aa.png">

**Comment by triniwiz** [comment]
I can add support to allow setting the userData on marker creation , but for now the following should get you running
```ts
const icon = ImageSource.fromResourceSync('Logo_marker');
const marker = this.map.addMarker({
position: { lat: 1, lng: 1},
icon});
marker.userData = { test: '1' };
console.log (marker.userData);
console.log(marker.userData.test);
```
