### ISSUE TITLE
@nativescript/google-maps Error on add Polilynes

### ISSUE THREAD

**Issue by juniorschen** [NativeScript/plugins#265]
Hello, I'm migrating my app to the new versions of nativescript. I'm finding it difficult to understand how this plugin works.
How can I add markers?
I can't understand when object to access and what properties, this was very easy with the old plugin
![image](https://user-images.githubusercontent.com/46031261/163811297-079d308e-0600-4d62-b626-f5d937f3d959.png)

![image](https://user-images.githubusercontent.com/46031261/163815185-b9219239-cb9d-4d27-a907-81d018b935d4.png)

**Comment by juniorschen** [comment]
![image](https://user-images.githubusercontent.com/46031261/163809270-695b960c-3f3d-450c-a15d-f67e0b2e6e41.png)

**Comment by juniorschen** [comment]
Changed to: 
![image](https://user-images.githubusercontent.com/46031261/163811130-0bb44222-9ab8-42a1-a0d5-284a0a918dd0.png)

**Comment by juniorschen** [comment]
Reciving: 
![image](https://user-images.githubusercontent.com/46031261/163811155-00021972-cd2d-46dd-b979-3f85979e9a61.png)
On:
![image](https://user-images.githubusercontent.com/46031261/163811215-34f15478-5fec-4154-b0be-b93e3f61e84a.png)

**Comment by juniorschen** [comment]
For bookmarks it works well, I was able to follow within this thread. Would you have fixed it only for markers and not polylines?
@triniwiz 
https://github.com/NativeScript/plugins/issues/233

**Comment by juniorschen** [comment]
![image](https://user-images.githubusercontent.com/46031261/163817870-7f3dde78-ff23-4812-ab27-c6baedd44bd6.png)
Probably the error occurred in one of these accesses, but I don't know what exactly should be done.

**Comment by triniwiz** [comment]
Fixed with https://github.com/NativeScript/plugins/commit/23b902d08e295911edd7955139a06e1a7ae0e38c
