### ISSUE TITLE
DatePickerField - JIT compilation failed for directive class DatePickerFieldDirective

### ISSUE THREAD

**Issue by kriefsacha** [NativeScript/plugins#269]
Hi,

I'm using latest nativescript angular, and i have an issue with @nativescript/datetimepicker

When i try to run the app at first it runs correctly but after a very few seconds i get this error:

> JIT compilation failed for directive class DatePickerFieldDirective
> An uncaught Exception occurred on "main" thread.
> Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
> Error: The directive 'DatePickerFieldDirective' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
> 
> The directive is part of a library that has been partially compiled.
> However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
> 
> Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
> Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
> or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
> File: (file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:31:12)
> 
> StackTrace: 
> getCompilerFacade(file:///data/data/org.nativescript.VisualyScan/files/app/vendor.js:18488:15)
> 	at ɵɵngDeclareFactory(file:///data/data/org.nativescript.VisualyScan/files/app/vendor.js:47517:22)
> 	at ./node_modules/@nativescript/datetimepicker/angular/fesm2015/nativescript-datetimepicker-angular.mjs(file:///data/data/org.nativescript.VisualyScan/files/app/vendor.js:172349:97)
> 	at _webpack_require_(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:28:33)
> 	at fn(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:222:21)
> 	at ./src/app/enter-exit-history/enter-exit-history.component.ts(file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:1843:95)
> 	at _webpack_require_(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:28:33)
> 	at fn(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:222:21)
> 	at ./src/app/app-routing.module.ts(file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:421:106)
> 	at _webpack_require_(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:28:33)
> 	at fn(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:222:21)
> 	at ./src/app/app.module.ts(file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:539:77)
> 	at _webpack_require_(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:28:33)
> 	at fn(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:222:21)
> 	at ./src/main.ts(file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:34:73)
> 	at _webpack_require_(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:28:33)
> 	at _webpack_exec_(file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:9005:39)
> 	at (file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:9006:189)
> 	at _webpack_require_.X(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:154:21)
> 	at (file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:9006:47)
> 	at (file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:9011:3)
> 	at require(:1:266)
> 
> 
> Error: The directive 'DatePickerFieldDirective' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
> 
> The directive is part of a library that has been partially compiled.
> However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
> 
> Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
> Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
> or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
> 
> StackTrace:
> java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
> Error: The directive 'DatePickerFieldDirective' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
> 
> The directive is part of a library that has been partially compiled.
> However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
> 
> Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
> Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
> or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
> File: (file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:31:12)
> 
> StackTrace: 
> getCompilerFacade(file:///data/data/org.nativescript.VisualyScan/files/app/vendor.js:18488:15)
> 	at ɵɵngDeclareFactory(file:///data/data/org.nativescript.VisualyScan/files/app/vendor.js:47517:22)
> 	at ./node_modules/@nativescript/datetimepicker/angular/fesm2015/nativescript-datetimepicker-angular.mjs(file:///data/data/org.nativescript.VisualyScan/files/app/vendor.js:172349:97)
> 	at _webpack_require_(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:28:33)
> 	at fn(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:222:21)
> 	at ./src/app/enter-exit-history/enter-exit-history.component.ts(file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:1843:95)
> 	at _webpack_require_(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:28:33)
> 	at fn(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:222:21)
> 	at ./src/app/app-routing.module.ts(file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:421:106)
> 	at _webpack_require_(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:28:33)
> 	at fn(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:222:21)
> 	at ./src/app/app.module.ts(file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:539:77)
> 	at _webpack_require_(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:28:33)
> 	at fn(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:222:21)
> 	at ./src/main.ts(file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:34:73)
> 	at _webpack_require_(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:28:33)
> 	at _webpack_exec_(file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:9005:39)
> 	at (file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:9006:189)
> 	at _webpack_require_.X(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:154:21)
> 	at (file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:9006:47)
> 	at (file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:9011:3)
> 	at require(:1:266)
> 
> 
> Error: The directive 'DatePickerFieldDirective' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
> 
> The directive is part of a library that has been partially compiled.
> However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
> 
> Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
> Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
> or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
> 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7011)
> 	at android.app.ActivityThread.access$1800(ActivityThread.java:274)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loop(Looper.java:233)
> 	at android.app.ActivityThread.main(ActivityThread.java:8030)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
> Caused by: com.tns.NativeScriptException: Error calling module function 
> Error: The directive 'DatePickerFieldDirective' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
> 
> The directive is part of a library that has been partially compiled.
> However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
> 
> Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
> Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
> or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
> File: (file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:31:12)
> 
> StackTrace: 
> getCompilerFacade(file:///data/data/org.nativescript.VisualyScan/files/app/vendor.js:18488:15)
> 	at ɵɵngDeclareFactory(file:///data/data/org.nativescript.VisualyScan/files/app/vendor.js:47517:22)
> 	at ./node_modules/@nativescript/datetimepicker/angular/fesm2015/nativescript-datetimepicker-angular.mjs(file:///data/data/org.nativescript.VisualyScan/files/app/vendor.js:172349:97)
> 	at _webpack_require_(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:28:33)
> 	at fn(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:222:21)
> 	at ./src/app/enter-exit-history/enter-exit-history.component.ts(file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:1843:95)
> 	at _webpack_require_(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:28:33)
> 	at fn(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:222:21)
> 	at ./src/app/app-routing.module.ts(file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:421:106)
> 	at _webpack_require_(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:28:33)
> 	at fn(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:222:21)
> 	at ./src/app/app.module.ts(file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:539:77)
> 	at _webpack_require_(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:28:33)
> 	at fn(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:222:21)
> 	at ./src/main.ts(file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:34:73)
> 	at _webpack_require_(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:28:33)
> 	at _webpack_exec_(file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:9005:39)
> 	at (file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:9006:189)
> 	at _webpack_require_.X(file:///data/data/org.nativescript.VisualyScan/files/app/runtime.js:154:21)
> 	at (file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:9006:47)
> 	at (file:///data/data/org.nativescript.VisualyScan/files/app/bundle.js:9011:3)
> 	at require(:1:266)
> 
> 
> Error: The directive 'DatePickerFieldDirective' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
> 
> The directive is part of a library that has been partially compiled.
> However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
> 
> Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
> Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
> or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
> 	at com.tns.Runtime.runModule(Native Method)
> 	at com.tns.Runtime.runModule(Runtime.java:689)
> 	at com.tns.Runtime.run(Runtime.java:681)
> 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
> 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
> 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7006)
> 	... 8 more

Package.json:

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "^12.2.5",
    "@angular/common": "^12.2.5",
    "@angular/compiler": "^12.2.5",
    "@angular/core": "^12.2.5",
    "@angular/forms": "^12.2.5",
    "@angular/platform-browser": "^12.2.5",
    "@angular/platform-browser-dynamic": "^12.2.5",
    "@angular/router": "^12.2.5",
    "@nativescript/angular": "^12.2.0",
    "@nativescript/background-http": "~5.0.0",
    "@nativescript/camera": "^5.0.12",
    "@nativescript/core": "^8.2.3",
    "@nativescript/datetimepicker": "^2.1.10",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/firebase-core": "^1.0.0-alpha.36",
    "@nativescript/firebase-crashlytics": "^1.0.0-alpha.36",
    "@nativescript/firebase-database": "^1.0.0-alpha.36",
    "@nativescript/firebase-storage": "^1.0.0-alpha.36",
    "@nativescript/geolocation": "~8.0.0",
    "@nativescript/imagepicker": "~1.0.0",
    "@nativescript/mlkit-barcode-scanning": "^1.0.0-alpha.8",
    "@nativescript/mlkit-core": "^1.0.0-alpha.8",
    "@nativescript/mlkit-face-detection": "^1.0.0-alpha.8",
    "@nativescript/theme": "^3.0.1",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@nstudio/nativescript-camera-plus": "^4.1.0",
    "@nstudio/nativescript-loading-indicator": "~4.0.0",
    "@nstudio/nativescript-pulltorefresh": "~3.0.0",
    "@nstudio/nativescript-snackbar": "~2.0.0",
    "nativescript-imagecropper": "~4.0.0",
    "nativescript-nfc": "~5.0.0",
    "nativescript-permissions": "^1.3.8",
    "nativescript-sound-kak": "^1.2.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-chart": "~9.0.0",
    "nativescript-ui-sidedrawer": "~10.0.0",
    "nativescript-webview-interface": "^1.4.2",
    "rxjs": "^7.4.0",
    "tns-platform-declarations": "^6.5.15",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-eslint/builder": "13.0.1",
    "@angular-eslint/eslint-plugin": "13.0.1",
    "@angular-eslint/eslint-plugin-template": "13.0.1",
    "@angular-eslint/schematics": "13.0.1",
    "@angular-eslint/template-parser": "13.0.1",
    "@angular/compiler-cli": "^12.2.5",
    "@nativescript/android": "8.2.2",
    "@nativescript/schematics": "~0.5.0",
    "@nativescript/types": "~8.1.0",
    "@nativescript/webpack": "~5.0.0",
    "@ngtools/webpack": "^12.2.5",
    "@types/jasmine": "^3.5.11",
    "@typescript-eslint/eslint-plugin": "5.3.0",
    "@typescript-eslint/parser": "5.3.0",
    "eslint": "^8.2.0",
    "typescript": "~4.3.5"
  },
  "readme": "NativeScript Application",
  "main": "./src/main.ts",
  "scripts": {
    "lint": "ng lint"
  }
}
```

app.module:
```
import { ErrorHandler, NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule, NativeScriptHttpClientModule, NativeScriptFormsModule, ModalDialogService, NativeScriptRouterModule, NativeScriptCommonModule } from "@nativescript/angular";
import { HttpClient, HttpHeaders } from "@angular/common/http";

import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";
import { NfcService } from "./services/nfc/nfc.service";
import { Auth0Service } from "./services/auth0/auth0.service";
import { LoginComponent } from './login/login.component';

import { ForgotPasswordComponent } from './forgot-password/forgot-password.component';
import { HomeComponent } from './home/home.component';
import { ScanComponent } from './scan/scan.component';
import { ParentsViewComponent } from './parents-view/parents-view.component';
import { SupportComponent } from './support/support.component';
import { ConvertService } from "./services/convert/convert.service";
import { DisableOnTapDirective } from "./disableOnTap-directive/disable-on-tap.directive";
import { PictureService } from "./services/picture/picture.service";


import { SettingsComponent } from './settings/settings.component';
import { SettingsIconComponent } from './settings-icon/settings-icon.component';
import { ScanQuestionsService } from "./services/ScanQuestionsService/ScanQuestions.service";
import { NativeScriptUISideDrawerModule } from "nativescript-ui-sidedrawer/angular";
import { EnterExitHistoryComponent } from "./enter-exit-history/enter-exit-history.component";
import { NativeScriptDateTimePickerModule  } from "@nativescript/datetimepicker/angular";
import { SchoolService } from "./services/school/school.service";
import { CreateEditAccessComponent } from "./create-edit-access/create-edit-access.component";
import { StatisticsComponent } from "./statistics/statistics.component";
import { NativeScriptUIChartModule } from "nativescript-ui-chart/angular";
import { StatisticsDetailsViewComponent } from "./statistics-details-view/statistics-details-view.component";
import { DocumentViewComponent } from "./document-view/document-view.component";
import { AddDocumentComponent } from "./add-document/add-document.component";
import { EnterExitPictureComponent } from "./enter-exit-picture/enter-exit-picture.component";
import { CustomCameraComponent } from "./custom-camera/custom-camera.component";
import { SearchProfilModalComponent } from "./search-profil-modal/search-profil-modal.component";
import { SearchIconComponent } from "./search-icon/search-icon.component";
import { VolumeComponent } from "./volume/volume.component";
import { SnackbarService } from "./services/snackbar/snackbar.service";
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { MLKitModule } from '@nativescript/mlkit-core/angular';

export function createTranslateLoader(http: HttpClient) {
    return new TranslateHttpLoader(http, "/assets/i18n/", ".json");
}

class MyErrorHandler implements ErrorHandler {
    handleError(error) {
        console.log(error?.stack || error)
    }
  }

@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        NativeScriptModule,
        AppRoutingModule,
        NativeScriptRouterModule,
        NativeScriptHttpClientModule,
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: createTranslateLoader,
                deps: [HttpClient]
            }
        }),
        NativeScriptFormsModule,
        NativeScriptUISideDrawerModule,
        NativeScriptCommonModule,
        NativeScriptDateTimePickerModule,
        NativeScriptUIChartModule,
        MLKitModule
    ],
    declarations: [
        AppComponent,
        LoginComponent,
        ForgotPasswordComponent,
        HomeComponent,
        ScanComponent,
        ParentsViewComponent,
        SupportComponent,
        DisableOnTapDirective,
        SettingsComponent,
        SettingsIconComponent,
        EnterExitHistoryComponent,
        CreateEditAccessComponent,
        StatisticsComponent,
        StatisticsDetailsViewComponent,
        DocumentViewComponent,
        AddDocumentComponent,
        EnterExitPictureComponent,
        CustomCameraComponent,
        SearchProfilModalComponent,
        SearchIconComponent,
        VolumeComponent
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ],
    providers: [
        NfcService,
        Auth0Service,
        ConvertService,
        PictureService,
        ModalDialogService,
        ScanQuestionsService,
        SchoolService,
        SnackbarService,
        {provide: ErrorHandler, useClass: MyErrorHandler}
    ],
    entryComponents: [ParentsViewComponent,StatisticsDetailsViewComponent,EnterExitPictureComponent,CustomCameraComponent,SearchProfilModalComponent]
})
export class AppModule { }
```

main.ts

```
// this import should be first in order to load some required settings (like globals and reflect-metadata)
import Theme from "@nativescript/theme";
import { runNativeScriptAngularApp, platformNativeScript } from '@nativescript/angular';

import { AppModule } from "./app/app.module";
import 'zone.js';
runNativeScriptAngularApp({
    appModuleBootstrap: () => platformNativeScript().bootstrapModule(AppModule),
  });

Theme.setMode(Theme.Light);
```

### ns --version : 8.2.3

Tell me if you need anything else. @NathanWalker  please help ! Thank you

**Comment by NathanWalker** [comment]
Hi @kriefsacha you could try any of the following three things most likely related:

1. Update to angular 13 - pretty painless really - can even `ns create sample --ng` and see anything you'd need like check `src/polyfills.ts` file and tsconfig setup

2. Can try adding `"@angular-devkit/build-angular": "^12.2.0"` to devDependencies 

3. Pin `"@nativescript/datetimepicker": "2.1.9",`

Then `ns clean` and run. Let us know.

**Comment by kriefsacha** [comment]
@NathanWalker i added @angular-devkit/build-angular (which i think when i saw a video they saied its not usefull anymore but seems like it is) and pinned 2.1.9 and it worked. Thank you SO much !

**Comment by NathanWalker** [comment]
@kriefsacha excellent cheers!
