### ISSUE TITLE
Long plugin titles wrap awkwardly

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/plugins#27]
If a plugin name is long, the title wraps and makes the tile look awkward. Suggest trying either removing "nativescript-" from all plugins, or decreasing font size.

**Comment by georgeedwards** [comment]
Line wrapping was defined by Nina in the wireframes - see:

[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/C1nbZ.png
I do agree that the titles look a bit awkward. I think it would be good to generate a title for the plugins, i.e. 
`nativescript-plugin-dev` -> plugin-dev` -> `Plugin Dev` ?

**Comment by rdlauer** [comment]
I see...I think maybe the preceding "nativescript-" is kind of distracting still, since it is part of every plugin pretty much.

I really like that idea of trying to come up with a plugin name that way. Seems reasonable to break on dashes. At least try it out!

**Comment by georgeedwards** [comment]
Awesome @NathanaelA what do you think?

**Comment by NathanaelA** [comment]
Hmm, that is very do-able.   I can modify the title to eliminate the "nativescript-" -- I'll get this done asap.

**Comment by NathanaelA** [comment]
Ok, @georgeedwards - there is a new property `shortName` which will have any `nativescript-` removed from it.    You still need the `name` property for linking to github & npm, since not every plugin has `nativescript-` in the beginning..

**Comment by georgeedwards** [comment]
Done - https://github.com/NativeScript/plugins/commit/9cc15d13febde58bb7f33f3a8313909f59f90ecc
