### ISSUE TITLE
@nativescript/google-maps: unable to add tile overlay

### ISSUE THREAD

**Issue by Semurak** [NativeScript/plugins#280]
Hello, I'm struggling to add a tile overlay to my map.

I've previously used another map package and solved the problem with native code, but I can't find a way to access the native map with this plugin.

After checking the plugin code, I found the method `addTileOverlay`, which should do the job for iOS and Android. BUT It does not work.

The constructor of `UrlTileProvider` / `TileProvider` accepts only one argument (size) and no tile url.
```
const tileUrl = "http://openfiremap.de/hytiles/{z}/{x}/{y}.png";
      
let tileProvider = new UrlTileProvider(512);
var options:TileOverlayOptions = {
      fadeIn: false,
      visible: true,
      tileProvider: tileProvider,
      zIndex: 10,
      transparency:0 
};

let tileOverlay = this.map.addTileOverlay(options)
```
Running the code above throws an error:
`Error: java.lang.NullPointerException: tileProvider must not be null.`

I am grateful for any help or code snippets. Thanks!

**Comment by triniwiz** [comment]
Nice catch it should be a callback + an optional size for the params like [this](https://github.com/NativeScript/plugins/blob/6d3207e924f13938c1aff52d0f83fbd6b89de5af/packages/google-maps/index.ios.ts#L1629)

**Comment by triniwiz** [comment]
You can try something like the following until a new version is published 
```ts
let tileProvider = new (UrlTileProvider as any)((x,y,zoom)=>{
return `http://openfiremap.de/hytiles/{zoom}/{x}/{y}.png`;
},512);
```

**Comment by Semurak** [comment]
Thank you for your quick reply and help! It works like a charm after adding `$`.

Here the working code:

```javascript
 let tileProvider = new (UrlTileProvider as any)((x,y,zoom) => {
        return `http://openfiremap.de/hytiles/${zoom}/${x}/${y}.png`;
 },512);
```

**Comment by triniwiz** [comment]
Yes I forgot those 😂 , will close this when I release the patch

**Comment by triniwiz** [comment]
Fixed with https://github.com/NativeScript/plugins/commit/76902fb9c3d132d230804a90844110418a284837
