### ISSUE TITLE
nativescript-ui-sidedrawer documentation

### ISSUE THREAD

**Issue by DanLatimer** [NativeScript/plugins#282]
The readme file for nativescript-ui-sidedrawer contains broken links to explain how the library can be used

![image](https://user-images.githubusercontent.com/1781415/171254432-f2b74e4f-345c-4a8d-a1d5-b1b680e48f34.png)

**Comment by wSedlacek** [comment]
@DanLatimer Thank you for the notice. We have fixed these links and they will be part of the next ui components release.
In the mean time checkout these links.

https://v7.docs.nativescript.org/ui/overview#nativescript-ui-overview
https://v7.docs.nativescript.org/angular/ui/overview#nativescript-ui-overview
https://v7.docs.nativescript.org/vuejs/ns-ui/overview
