### ISSUE TITLE
@nativescript/google-maps - userData not always returned in created object

### ISSUE THREAD

**Issue by rljdavies** [NativeScript/plugins#289]
Firstly, thanks, so relieved not to be stuck on crucial but dormant plugins.  

I migrated to this and, aside from a bit of extra work storing created objects locally (can't query the map object and find eg markers or shapes based on userData....actually it's a lot more complete than the previous most popular google maps plugin.

There's a small bug....when adding a marker the userData specified in marker options is returned on the created object, but when I add a circle it is not.  I haven't tested polygons, polylines or ground overlays. 

Also, tiny point of clarity/consistency....should....

	addMarker(marker: MarkerOptions): Marker;

...instead be....

	addMarker(options: MarkerOptions): Marker;

Thanks again, great work.

rgds
R

**Comment by triniwiz** [comment]
Platforms tested ?

**Comment by rljdavies** [comment]
Just iOS so far.

Thanks
R

**Comment by triniwiz** [comment]
Fixed here : https://github.com/NativeScript/plugins/commit/4c8be91cb89d41ef4c9ee977383e795b5f434f3e

**Comment by rljdavies** [comment]
many thanks.
