### ISSUE TITLE
[@nativescript/local-notifications] Crash on iOS when app is in foreground

### ISSUE THREAD

**Issue by damianocorrado** [NativeScript/plugins#29]
Crash on iOS when a notification is scheduled and app is in foreground.
Even with last version (5.1.0)

"@nativescript/ios": "7.0.0",
"@nativescript/core": "7.0.9",

nativescript-cli version 7.0.8

**Comment by nicmanzini** [comment]
NativeScript encountered a fatal error: Uncaught RangeError: Maximum call stack size exceeded
at

**Comment by rob4226** [comment]
@damianocorrado @NathanWalker @EddyVerbruggen I am also having the same issue where iOS crashes if the notification is scheduled and app is in foreground. Is there a work around at the moment for iOS? Thank you.

**Comment by damianocorrado** [comment]
> @damianocorrado @NathanWalker @EddyVerbruggen I am also having the same issue where iOS crashes if the notification is scheduled and app is in foreground. Is there a work around at the moment for iOS? Thank you.

You can clone plugin repo and use this component as a local plugin fixing **userNotificationCenterWillPresentNotificationWithCompletionHandler** method in index.ios.js file

```
userNotificationCenterWillPresentNotificationWithCompletionHandler(center, notification, completionHandler, next) {
        if (notification.request.content.userInfo.valueForKey('__NotificationType') !== 'nativescript-local-notifications' || notification.request.trigger instanceof UNPushNotificationTrigger) {
            next();
            return;
        }
        this.receivedInForeground = true;
        /*
        if (notification.request.content.userInfo.valueForKey('forceShowWhenInForeground') || notification.request.content.userInfo.valueForKey('priority')) {
            completionHandler(1 /* Badge */ | 2 /* Sound */ | 4 /* Alert */);
        }
        else {
            completionHandler(1 /* Badge */ | 2 /* Sound */);
        }
        */
    }

**Comment by rob4226** [comment]
Thank you, I had a feeling this function was the issue. When I commented those lines out I didn't get any notification and when I just tried calling `completionHandler(1)` or `completionHandler(4)` it crashes the app immediately so at least we know what it is. Does anyone know why call `completionHandler()` would crash the app??

**Comment by bradmartin** [comment]
Fix is in the works. Issue comes from shared-delegate, a dependency for local-notifications and firebase. Thanks to @edusperoni for helping to track it down. Should have a PR with bug releases pushed soon.

**Comment by rob4226** [comment]
That's great news! Thanks!!

**Comment by damianocorrado** [comment]
Great work. Thank you
