### ISSUE TITLE
[Biometrics] Verification fails after wrong fingerprint the first time

### ISSUE THREAD

**Issue by Martinn1996** [NativeScript/plugins#294]
When using the fingerprint scanner, if after the first time the verification fails, and then after succeeds, it still counts as "failed". But when using the pin/pattern, it does succeeds after failing the first time.

**Comment by jcassidyav** [comment]
Which OS?

And how are you calling it?  i.e. what params are you passing.

**Comment by Martinn1996** [comment]
On Android, `await this.biometricAuth.verifyBiometric({pinFallback: true});`. So the first when scanning with my wrong finger, it says "Fingerprint not recognized", and then when using the correct fingerprint, it succeeds, but it doesn't execute the code afterwards.

**Comment by jcassidyav** [comment]
And which version of android ?

**Comment by Martinn1996** [comment]
12

**Comment by jcassidyav** [comment]
Yeah I see the issue, looks like the code in  onAuthenticationFailed should be removed, it shouldn't be rejecting the promise, I'll do a fix when I get a chance to test it in the various scenarios.

**Comment by NathanWalker** [comment]
published with 1.0.1
