### ISSUE TITLE
RWD breakpoint clarity

### ISSUE THREAD

**Issue by jlooper** [NativeScript/plugins#30]
The breakpoints seem a little iffy as you shrink your browser down. I'm guessing we should follow Bootstrap's media queries to break the view into a single card view (http://getbootstrap.com/css/)

<img width="878" alt="screenshot 2017-01-16 15 20 57" src="https://cloud.githubusercontent.com/assets/1450004/21999426/11be3718-dc08-11e6-8ae9-a1276fc4b504.png">

**Comment by georgeedwards** [comment]
should be fixed
