### ISSUE TITLE
Inner page right nav

### ISSUE THREAD

**Issue by jlooper** [NativeScript/plugins#31]
The inner page where you read all about your plugin has some issues on the right nav:

<img width="1105" alt="screenshot 2017-01-16 15 22 02" src="https://cloud.githubusercontent.com/assets/1450004/21999497/74245b12-dc08-11e6-8ced-43efe7a7a5f9.png">

**Comment by georgeedwards** [comment]
Should be fixed (npm command box + horizontal overflow). Although, Nina hasn't mentioned how to deal with vertical overflowing on the sidebar. Either it isn't fixed as I currently have it (then for long readme plugins there is a white bar along the right hand side) or we have some scrolling. Thoughts?

**Comment by georgeedwards** [comment]
Although, Nina hasn't mentioned how to deal with vertical overflowing on the sidebar. Either it isn't fixed as I currently have it (then for long readme plugins there is a white bar along the right hand side) or we have some scrolling. Thoughts?
