### ISSUE TITLE
[@nativescript/contacs][iOS] 'note' should not be included in keysToFetch during delete()

### ISSUE THREAD

**Issue by fpaaske** [NativeScript/plugins#324]
Since `note` is included, and most apps will be missing the required entitlements for this field, no contacts will be returned in the query for the contact to delete.

In fact, I think no fields are necessary to fetch when the goal is to delete the contact.

https://github.com/NativeScript/plugins/blob/dca89bb464e26115d56e4a028fd774ef48eb6589/packages/contacts/models/contact.ios.ts#L222

The same goes for fetch operations, the `note` probably shouldn't be included by default. But that's already configurable for the API-user, so it's not that critical 🙂 

According to apple documentation, to access the contact notes you'll have to explicitly declare that you need to do this (with an entitlement), and I'm pretty sure you'll be going through a tougher review process if you do.

https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_contacts_notes

> Before you submit an app with this entitlement to the App Store, you need to get permission to use the entitlement. Request permission at https://developer.apple.com/contact/request/contact-note-field.

**Comment by NathanWalker** [comment]
Agreed thanks for tracking this - it’s always been chore dealing with the note capability when it’s rarely needed in common cases. Would you like to submit a PR to just remove from defaults? As you mention that can be customized per case if someone does need it.
