### ISSUE TITLE
[@nativescript/local-notifications] [Android] Requires runtime permission dialog to allow notifications.

### ISSUE THREAD

**Issue by 7ammer** [NativeScript/plugins#336]
It appears that android13 (SDK33) now requires a runtime permission for setting local notifications:
https://developer.android.com/develop/ui/views/notifications/notification-permission#user-choice

I get this error when running the `LocalNotifications.schedule` method: **`Permission not granted.`**.

I've tried just adding this permission: `<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>` but nothing changes.

If I grant notification permissions to the app via `App info > Permissions` then everything works fine again.

**Comment by robertosw** [comment]
Got the same problem, it does not matter at all where in the code you try .requestPermission, it will always return false because there will be no Popup triggered in Android.
As soon as you manually allow Notifications in the App Settings in Android, .requestPermission will always return true

**Comment by tobiAdBr** [comment]
Got the same problem. Looks like the permissions dialog has to be implemented manually

**Comment by XR-115** [comment]
Hello! I would just like to comment that if you have problems with these permissions that have not been granted, you could check the android version of your project **"@nativescript/android"** to see if it is compatible, you can run **ns info** and validate the updated version of your android
