### ISSUE TITLE
Change code highlighting color on plugin detail pages

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/plugins#34]
Light blue seems out of place. Suggest Nina gives some ideas for alternate colors that better match the color scheme.

**Comment by georgeedwards** [comment]
Awesome, will you ask her about this or shall I?

**Comment by rdlauer** [comment]
I'll forward this to her as I don't believe she has a GH account.

**Comment by rdlauer** [comment]
Let's change the `pre` and `code` highlighting to this:
```
background-color: #efefef;
border: 1px solid #e8e8e8;
border-radius: 3px;
```

**Comment by georgeedwards** [comment]
Done - https://github.com/NativeScript/plugins/commit/77bcdf567fff263d1408cf17ab349e40eee21a4e
