### ISSUE TITLE
[@nativescript/datetimepicker] angular ios spinner style seems to break after first use (ns-dark)

### ISSUE THREAD

**Issue by jamescodesthings** [NativeScript/plugins#34]
# Overview
When using DateTimePickerFields in nativescript angular on ios. The first time the spinner opens it's styled exactly as expected.

The second time it appears it's backed off to light styling? or something else has borked.
Styling is using the default styling from `@nativescript/theme` for the `.date`

## Env
```
ios 14 sim.
├── nativescript@7.0.11
├── @nativescript/angular@10.1.7
├── @nativescript/theme@3.0.0
├── @nativescript/ios@7.0.4
├── @nativescript/datetimepicker@2.0.4
```

| First Time | Second Time |
| ---------- | ------------- |
| ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-23 at 17 37 22](https://user-images.githubusercontent.com/32203362/97030295-763cd100-1556-11eb-8613-22efaa0233eb.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-23 at 17 38 11](https://user-images.githubusercontent.com/32203362/97030353-8ce32800-1556-11eb-9110-94a9b05fc1bc.png) |

**Comment by justinkurtz** [comment]
I've run into this issue as well. I have to disable dark mode or find another date time picker.

**Comment by bradmartin** [comment]
I'm not 100% on this but this might have been fixed previously. If not the following is the approach I take and have added to the documentation for styling the presented control for dark/light mode on the device.

```ts
import { DateTimePicker, DateTimePickerStyle } from '@nativescript/datetimepicker';
import { Application, Button } from '@nativescript/core';

export function someButtonTapToOpenThePicker(args) {
	const dateTimePickerStyle = DateTimePickerStyle.create(args.object as any);

    // This example handles styling the calendar for light and dark mode of the device settings
	if (Application.systemAppearance() === 'dark') {
      // style for dark mode
      dateTimePickerStyle.buttonsBackgroundColor = new Color('#202125');
      dateTimePickerStyle.dialogBackgroundColor = new Color('#202125');
      dateTimePickerStyle.titleTextColor = new Color('#fff');
      dateTimePickerStyle.buttonsTextColor = new Color('#0067a6');
      dateTimePickerStyle.spinnersBackgroundColor = new Color('#202125');
      dateTimePickerStyle.spinnersTextColor = new Color('#fff');
    } else {
      // style for light mode
      dateTimePickerStyle.buttonsBackgroundColor = new Color('#fff');
      dateTimePickerStyle.dialogBackgroundColor = new Color('#fff');
      dateTimePickerStyle.titleTextColor = new Color('#0067a6');
      dateTimePickerStyle.buttonsTextColor = new Color('#0067a6');
      dateTimePickerStyle.spinnersBackgroundColor = new Color('#fff');
      dateTimePickerStyle.spinnersTextColor = new Color('#0067a6');
    }

     DateTimePicker.pickDate(
      {
        context: (args.object as Button)._context,
        date: yourDateValue
        minDate: subYears(new Date(), 10),
        maxDate: new Date(),
        title: 'DatePicker'
        okButtonText: 'Okay',
        cancelButtonText: 'Cancel',
        locale: 'en'
      },
      dateTimePickerStyle
    ).then((result) => {
        // handle the result
    })
}
```

**Comment by alexander-mai** [comment]
I found the reason for the bright picker view.

In `datetimepicker/common.ts` are the css classes copied for styling the picker.
```typescript
	// line 95 - 100
	if (view.className) {
		let classNames = view.className.split(' ');
		classNames.forEach((element) => {
			tempView.cssClasses.add(element);
		});
	}
```

On first run`view.className` equals `ns-dark`and on second run `ng-valid ng-touched ng-dirty`. The class `ns-dark`is remvoved and the style is therefore switched to bright mode.

I could fix the problem by copying the content of `view.cssClasses`to tempView.cssClasses.
```typescript
	if (view.cssClasses && view.cssClasses.length > 0) {
		view.cssClasses.forEach((element) => {
			tempView.cssClasses.add(element);
		});
	}
```

The array `view.cssClasses`contains on first run `[ns-ios, ns-phone, ns-portrait, ns-dark, a11y-fontscale-100, a11y-fontscamel-m, a11y-service-disabled]`and beginning with the second run `[ns-ios, ns-phone, ns-portrait, ns-dark, a11y-fontscale-100, a11y-fontscamel-m, a11y-service-disabled, ng-valid, ng-touched, ng-dirty]`.

On Android it works the same way, but there I can't see the bright background problem.
I could also see no issue on android with my fix. It works well for me.
