### ISSUE TITLE
http-background: Error -1, does not show the detail of the exception

### ISSUE THREAD

**Issue by vicmasa** [NativeScript/plugins#340]
Hello everyone.

Thanks for your help, the plugin "http-background" works great, but when we want to show the user the detail of the error returned by the web service, it only shows us ERROR -1. Please, can you return the error detail, as HTTP requests do.

Thanks.

**Comment by vicmasa** [comment]
Hi.
The error event does not return the status code or the message of the Web Service.
It is necessary to obtain the status code, and the error message, in order to define the actions to follow in the app, but currently it only returns error -1.

Thanks.

**Comment by myjajat** [comment]
After years of good, now I have the same issue in 6.0.1. 
@vicmasa what have you done to solve that? 
Only Error -1, without any message, totally broke my brain!
Please help

**Comment by Devendra0110** [comment]
Did you found any solution for it?
