### ISSUE TITLE
Processing: support for "iosDummyWrapper" and "androidDummyWrapper" 

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/plugins#35]
In an attempt to cleanup mis-reporting plugins (i.e. plugin reporting they support 'X' platform) when all they have is a dummy wrapper to keep the plugin from crashing on 'X' platform.

Add support to see if these fields exists and give bonus points for this ability.

**Comment by NathanaelA** [comment]
We might want to have a display icon for these; or we can just at this moment pretend this data is just for scoring.  Thought?

**Comment by rdlauer** [comment]
Any idea of the scope of this issue? Like do "a lot" of plugins really do this? Seems like a big time cheat!

**Comment by NathanaelA** [comment]
Actually several plugins do this; I can probably name at least a dozen off the top of my head that I know do this.   The initial idea that the author had is not a bad idea; and I consider the wrapper a good idea.     the user doesn't have to special case the code.   So a dummy wrapper can be a good thing.    However, when the author claims that the plugin ALSO works for "android" or "ios" and actually doesn't do anything on those platforms (because it is a dummy wrapper), this will mislead people into thinking the plugin works for something it doesn't.   And this is the mis-reporting I am talking about.  

I have no idea if we want to show those with a wrapper with a different icon; or just show them as "android" only (or "ios" only) . And leave it at that, the idea for adding dummyWrapper support was to help plugin authors get more points by properly reporting it, as I like clean correct data.   ;-)

**Comment by NathanaelA** [comment]
Btw, the code has been added to the processor for this.   And the value is exposed to the clients of the api if they want it.

**Comment by rdlauer** [comment]
IMO for now we should just exclude the OS support on the plugin detail page for these cases. We could think about an icon/score-- for v2...
