### ISSUE TITLE
[@nativescript/google-maps] no tap event for polygon, polyline or circle on iOS

### ISSUE THREAD

**Issue by BozzaDaniel** [NativeScript/plugins#350]
The tap events for polygon, polyline and circle never fires on iOS because the notify event never occurs for them, only the ground overlay does:

https://github.com/NativeScript/plugins/blob/2e51a2feec6bf7312e157d677d92193ffb326971/packages/google-maps/index.ios.ts#L300-L308

The code needs to be updated to check if overlay is an instance of GMSPolygon, GMSPolyline or GMSCIrcle and send the notify event.

**Comment by jlafitte** [comment]
~~I need this fix in my app but it doesn't look like the version on NPM is updated with this.  What's the best way to get it?~~

Never mind, I'm stupid.  I did have it, just was looking in the wrong file.
