### ISSUE TITLE
[@nativescript/geolocation] PRIORITY_HIGH_ACCURACY' of undefined

### ISSUE THREAD

**Issue by Woongsik** [NativeScript/plugins#364]
"@nativescript/core": "^8.3.6",
"@nativescript/geolocation": "^8.1.0",
"@nativescript/android": "~8.3.1",

enableLocationRequest()
.then(() => { 
   console.log("Enabled");
}).catch((error: Error) => {
  console.log("Error", error);
});

Error: Cannot enable the location service. TypeError: Cannot read property 'PRIORITY_HIGH_ACCURACY' of undefined

I cannot make the location enabled. Any solution for this?

**Comment by CatchABus** [comment]
@Woongsik Hello. Can you try `ns clean` and rebuild your app?
Also, are you using any other plugin like maps?

**Comment by jajatismail** [comment]
i got exactly the same issue.

"@nativescript/core": "^8.3.6",
"@nativescript/geolocation": "^8.1.0",
"@nativescript/android": "8.1.1",

**Comment by CatchABus** [comment]
@Woongsik @jajatismail Do your apps contain this configuration inside gradle settings?
```gradle
android {  
  // other stuff here

  project.ext {
    googlePlayServicesVersion = "mynewversionexample"
  }
}
```

If so, try removing it and hit `ns clean` again.
An old `googlePlayServicesVersion` may download libraries that are no longer compatible with plugin.
If you really need it, you can set version to `21.+` and see how it goes.
```gradle
android {  
  // other stuff here

  project.ext {
    googlePlayServicesVersion = "21.+"
  }
}
```

**Comment by Woongsik** [comment]
@CatchABus Thanks for the help. Removing it and working again. I need to take a look if there is something else from this but so far, it seems working great. Thanks!

**Comment by liamcharmer** [comment]
> 

**Just incase anyone is a bit silly like me and forgets about having a before-plugins.gradle, check there also**
