### ISSUE TITLE
Change header links

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/plugins#37]
- Let's remove the "home" link when you are on the home page.
- Let's create a short term list of header links to be:
  - View All Plugins (link to home, just on plugin detail page)
  - [Create a Plugin](https://docs.nativescript.org/plugins/plugins)
  - [NativeScript Home](https://www.nativescript.org/)
- Let's right-align these links too

I'm open to feedback here, but this could just be a start.

**Comment by jlooper** [comment]
How about also a link to NativeScript Docs and Help (which can point to the forum)

**Comment by georgeedwards** [comment]
@NathanWalker do you want to take this one or shall I?
