### ISSUE TITLE
Minor header/search bar formatting changes

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/plugins#38]
- Remove padding from `.search-container` to give equal padding on left, right, and bottom
- Alter the padding around header elements to be equal. For example, in the provided image, I'm showing (with yellow dots) all of the padding that should be equal (using the padding on left/bottom of search bar as the reference value):
![image](https://cloud.githubusercontent.com/assets/1918280/22073711/a66b23d0-dd6b-11e6-9a9b-c0ef4e694d56.png)

- Vertically align the hamburger icon with the text:
![image](https://cloud.githubusercontent.com/assets/1918280/22073772/d7ae6826-dd6b-11e6-9e24-14f1d00d0b74.png)

- I'm very concerned the "filter" icon is not nearly noticeable enough. Can we play around with ideas here? Maybe add the text "Filters" next to or part of the icon?

**Comment by jlooper** [comment]
I'm actually confused about these icons. If I click the hamburger icon, I see the list icon and a list, and it toggles fine. What's that thing on the right? Is that the filter icon? If so, I don't think it's doing anything except toggling to list (can we remove it?)

<img width="1291" alt="screenshot 2017-01-18 12 22 03" src="https://cloud.githubusercontent.com/assets/1450004/22075175/f02a770c-dd78-11e6-8108-32157b844fa6.png">

**Comment by rdlauer** [comment]
Filter icon isn't working yet (see #26)

**Comment by georgeedwards** [comment]
Done - https://github.com/NativeScript/plugins/commit/467d6f701d1b706745278d9161296c79a42f5d84
