### ISSUE TITLE
[@nativescript/geolocation] IOS enableLocationRequest hangs forever if 'Alow Once' is selected

### ISSUE THREAD

**Issue by valera1401** [NativeScript/plugins#386]
`case CLAuthorizationStatus.kCLAuthorizationStatusAuthorizedWhenInUse:
                if (this._resolve && !this.authorizeAlways) {
                    LocationMonitor.stopLocationMonitoring(this.id);
                    this._resolve();
                }
                break;`

The problem is in this code.

If enableLocationRequest function was called with parameter always == true and 'Allow once' option is selected in the permission popup, then AuthorizationStatus will be kCLAuthorizationStatusAuthorizedWhenInUse and resolve will never be called.

**Comment by NathanWalker** [comment]
Fixed in 8.2.1
