### ISSUE TITLE
social-share | RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mandrag0ra** [NativeScript/plugins#39]
When I use social-share with tabview I get the following error message when I try to share a url, text or an image: ` RangeError: Maximum call stack size exceeded`

To reproduce the error, simply create a new typescript project with ns create and choose the `Tabs` template. From any view, try to share a URL, text or image.

**env:**
nativescript @7.0.10
@nativescript/core @7.0.13
@nativescript/ios @7.0.4

**Comment by nice2seeu** [comment]
same problem

**Comment by mandrag0ra** [comment]
I would like to mention that everything works fine on android.

**Comment by NathanWalker** [comment]
Fixed with `@nativescript/core` 7.1.4 --- the template apps all use ~7.1.0 so just `ns clean` on the sample you had created or creating a new and will be good now. Thanks for reporting.
