### ISSUE TITLE
Don't stretch the plugin description text in the title

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/plugins#39]
![image](https://cloud.githubusercontent.com/assets/1918280/22073923/4f714e6e-dd6c-11e6-941e-1cc4446a2c31.png)

Remove `text-align: justify` property.

**Comment by georgeedwards** [comment]
Can we discuss this? I am doing that to make a slightly work-around method of getting the multi-line ellipsis working. I can probably find another way of doing that if it is an issue...

**Comment by rdlauer** [comment]
Can you give me an example of a multi-line ellipsis? Curious to see if that's an issue we care enough about.

**Comment by georgeedwards** [comment]
So it looks like this:
[![enter image description here][1]][1]

rather than this (with the long gap before the ellipsis):
[![enter image description here][2]][2]


  [1]: https://i.stack.imgur.com/mUXD1.png
  [2]: https://i.stack.imgur.com/FIsUn.png

**Comment by rdlauer** [comment]
I see. Admitting ignorance to how you are doing this in code, is it possible to append the ellipsis to the text directly after x number of characters/words?

IMO in most cases the text looks better left-justified, so it would be nice if we could get this working.

**Comment by georgeedwards** [comment]
I can have a look. It's surprisingly difficult, as the css `text-overflow` property only works on one line and it's hard to do in JS as number of chars isn't responsive.

**Comment by georgeedwards** [comment]
@rdlauer Can I close this in favour of a better solution for v2? Or is this something you want me to do for this release?

**Comment by rdlauer** [comment]
Yeah let's shelve this for now. I would consider even dropping the ellipsis and left justifying the text, but we can talk about it later.
