### ISSUE TITLE
[@nativescript/google-maps]  How to find if the marker is within bounds 

### ISSUE THREAD

**Issue by harshakuk** [NativeScript/plugins#395]
Is there a way to get the bounds of map? I am trying to compute if the marker is inside the visible viewport or not?

Maybe the bounds can be found using `this.googleMap.projection.visibleRegion()`
but how do i compute if the marker is located within the visible bounds or not?

**Comment by herefishyfish** [comment]
Hey, there are a couple of ways to achieve this. 

When in doubt having a look at the Android and iOS Map documentation always helps. 
https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/Projection
https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_projection

The NativeScript bindings for GoogleMaps classes are mostly wrappers for the native objects, this means we can access the native object and handle these seperately acheive the desired result.

As you can see the Android/iOS classes are a little bit different, iOS has a `containsCoordinate` method where Android doesn't.
We can dive deeper into the Android visibleRegion and see that it has a latLngBounds which has a `contains` method - that should do the trick.

So we can go down this route which might look something like this:
```ts
// `.native` currently isn't exported in the types but does exist on the object, I'll fix this later but for now cast it as any to stop TS complaining.
const projection = this.map.projection as any;
let inBounds = false;

if (isAndroid) {
  const region = projection.native.getVisibleRegion();
  inBounds = region.latLngBounds.contains(
    new com.google.android.gms.maps.model.LatLng(
      this.position.lat,
      this.position.lng
    )
  );
} else {
  const region = projection.native;
  inBounds = region.containsCoordinate(
    CLLocationCoordinate2DMake(this.position.lat, this.position.lng)
  );
}

if (inBounds) {
  console.log('point is in bounds');
} else {
  console.log('point is not in bounds');
}
```


Else we can use the methods that are supplied currently and process this ourselves
```ts
const projection = this.map.projection;

const bounds = projection.visibleRegion();

// check if point is in bounds
// this code assumes that the bounds are a rectangle without any rotation
if (
  bounds.nearLeft.lat <= this.position.lat &&
  this.position.lat <= bounds.farRight.lat &&
  bounds.nearLeft.lng <= this.position.lng &&
  this.position.lng <= bounds.farRight.lng
) {
  console.log('JS: point is in bounds');
} else {
  console.log('JS: point is not in bounds');
}
```

Stackblitz: https://stackblitz.com/edit/nativescript-stackblitz-templates-q9ako4?file=src%2Fapp%2Fmap.component.ts&title=NativeScript%20Starter%20Angular

**Comment by harshakuk** [comment]
> Hey, there are a couple of ways to achieve this.
> 
> When in doubt having a look at the Android and iOS Map documentation always helps. https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/Projection https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_projection
> 
> The NativeScript bindings for GoogleMaps classes are mostly wrappers for the native objects, this means we can access the native object and handle these seperately acheive the desired result.
> 
> As you can see the Android/iOS classes are a little bit different, iOS has a `containsCoordinate` method where Android doesn't. We can dive deeper into the Android visibleRegion and see that it has a latLngBounds which has a `contains` method - that should do the trick.
> 
> So we can go down this route which might look something like this:
> 
> ```ts
> // `.native` currently isn't exported in the types but does exist on the object, I'll fix this later but for now cast it as any to stop TS complaining.
> const projection = this.map.projection as any;
> let inBounds = false;
> 
> if (isAndroid) {
>   const region = projection.native.getVisibleRegion();
>   inBounds = region.latLngBounds.contains(
>     new com.google.android.gms.maps.model.LatLng(
>       this.position.lat,
>       this.position.lng
>     )
>   );
> } else {
>   const region = projection.native;
>   inBounds = region.containsCoordinate(
>     CLLocationCoordinate2DMake(this.position.lat, this.position.lng)
>   );
> }
> 
> if (inBounds) {
>   console.log('point is in bounds');
> } else {
>   console.log('point is not in bounds');
> }
> ```
> 
> Else we can use the methods that are supplied currently and process this ourselves
> 
> ```ts
> const projection = this.map.projection;
> 
> const bounds = projection.visibleRegion();
> 
> // check if point is in bounds
> // this code assumes that the bounds are a rectangle without any rotation
> if (
>   bounds.nearLeft.lat <= this.position.lat &&
>   this.position.lat <= bounds.farRight.lat &&
>   bounds.nearLeft.lng <= this.position.lng &&
>   this.position.lng <= bounds.farRight.lng
> ) {
>   console.log('JS: point is in bounds');
> } else {
>   console.log('JS: point is not in bounds');
> }
> ```
> 
> Stackblitz: https://stackblitz.com/edit/nativescript-stackblitz-templates-q9ako4?file=src%2Fapp%2Fmap.component.ts&title=NativeScript%20Starter%20Angular

Thanks a mil, that was helpful.

**Comment by herefishyfish** [comment]
#399 implements this in the projection class.
```ts
projection.containsCoordinate({ lat: -32.123, lng: 123.123 });
```
