### ISSUE TITLE
[@nativescript/imagepicker] imagepicker partly broken by scoped storage (Android 11)?

### ISSUE THREAD

**Issue by boutier** [NativeScript/plugins#41]
Taking a photo works as expected, but selecting a photo from the gallery doesn't seem to work anymore (see log below — as comment).

This issue duplicates an issue from the old _imagepicker_ repository : https://github.com/NativeScript/nativescript-imagepicker/issues/309
And seems related to https://github.com/NativeScript/NativeScript/issues/7866

```
% ns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.0.11 version and is up to date.
✔ Component @nativescript/core has 7.0.13 version and is up to date.
✔ Component @nativescript/ios has 7.0.5 version and is up to date.
✔ Component @nativescript/android has 7.0.1 version and is up to date.
```

```
    Imagepicker.create({ mode: 'multiple' })
      .authorize()
      .then(() => context.present())
      .then((selection) => {
        selection.forEach((imageAsset) => {
          console.log(imageAsset);
                // JS: {
                // JS:   "_observers": {},
                // JS:   "_options": {
                // JS:     "keepAspectRatio": true,
                // JS:     "autoScaleFactor": true
                // JS:   },
                // JS:   "_android": "/storage/emulated/0/DCIM/Camera/NSIMG_20200928_161415.jpg"
                // JS: }
          ImageSource.fromAsset(imageAsset)
                // Asset '/storage/emulated/0/DCIM/Camera/NSIMG_20200928_161415.jpg' cannot be found.
```

Note : The ImagePicker.present() function gets a URI (of the form "content://…") that is converted by the _imagepicker_ into an absolute path (as above), but the ImageSource seems unable to interpret it. I first thought that maybe `ImageAsset.android` should be a URI rather than an absolute path (and ImageSource being able to interpret it). But some API seems to be compatible with absolute paths [1], so I'm not even sure anymore it's an _imagepicker_ bug rather than a `ImageSource` bug… anyway, posting here since the bug arise when using _imagepicker_.

[1] From https://developer.android.com/about/versions/11/privacy/storage
> #### Access files using direct file paths and native libraries
>
>To help your app work more smoothly with third-party media libraries, Android 11 allows you to use APIs other than the MediaStore API to access media files from shared storage using direct file paths. These APIs include the following:
>
> * The File API.
> * Native libraries, such as fopen().

**Comment by DanielDent** [comment]
I think this may be the same issue I've seen in the case of taking a photo using the camera plugin

https://github.com/NativeScript/nativescript-camera/issues/252#issuecomment-725917612

"I believe the issue is that the plugin is currently only compatible with API level 28. At API level 29, adding android:requestLegacyExternalStorage="true" to the app manifest is available as a workaround, but this option is no longer available at API level 30."

**Comment by benediktveith** [comment]
Can confirm.

ImagePicker uses `getExternalMediaDirs` inside its `_calculateFileUri` function, which is deprecated since API Level 30.

Fyi @NathanWalker

**Comment by slejnej** [comment]
Same problem with diff specs:
```
% ns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.1.2 version and is up to date.
✔ Component @nativescript/core has 7.1.4 version and is up to date.
✔ Component @nativescript/ios has 7.2.0 version and is up to date.
✔ Component @nativescript/android has 7.0.1 version and is up to date.
```
in app.gradle:
```
android {
  defaultConfig {
    generatedDensities = []
    minSdkVersion 23
    targetSdkVersion 29
    compileSdkVersion 29
  }
}
```

in references.d.ts
```
/// <reference path="./node_modules/@nativescript/types-ios/index.d.ts" />
/// <reference path="./node_modules/@nativescript/types-android/lib/android-29.d.ts" />
```

`ns build android` produces error:
```
Execution failed for task ':verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     /home/projects/DEV/app/platforms/tempPlugin/imagepicker/src/main/AndroidManifest.xml:4:3-61: AAPT: error: attribute android:requestLegacyExternalStorage not found.
```

**Comment by itsmerockingagain** [comment]
@NathanWalker we are facing this issue in Nativescript 6 also, can you please help on this.
