### ISSUE TITLE
Minor changes to formatting of plugin detail content

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/plugins#42]
- [x] - Padding around content/sidebar should be equal (use the top/right padding of sidebar as the reference):
![image](https://cloud.githubusercontent.com/assets/1918280/22074432/f7f21676-dd6d-11e6-96c7-403f6651f320.png)

- [x] - Expand the content area to fill available area (keeping in mind padding/margin we would want to keep between content and sidebar)

- [x] - Bold h2 tag

- [x] - Change color of `.detail h2` to lightgrey

- [x] - Numerous formatting issues for content (use image below as reference from [this plugin](http://plugins-94874.onmodulus.net/plugin/nativescript-badge-button))
  - Remove `margin-top` from h3
  - Tables are not being displayed correctly
  - Broken images
  - Remove `margin` from `pre` tags to prevent code samples from blending together

![image](https://cloud.githubusercontent.com/assets/1918280/22074722/f72e1d74-dd6e-11e6-8a04-d9b2b6bfe637.png)

**Comment by georgeedwards** [comment]
Padding done - https://github.com/NativeScript/plugins/commit/3d43282e7ffe76eeb01a686a1f384ef2e5669458
h3 & pre tags & h2 done - https://github.com/NativeScript/plugins/commit/2ee0c5418d82081bb7c1da4da313092b4f489e7b

@NathanWalker Could you look at the pictures issue?

I'll have a look at why tables aren't rendering - I expect it's a Github flavoured md thing.

**Comment by georgeedwards** [comment]
tables done - https://github.com/NativeScript/plugins/commit/949186bba9ca8a6634c11ba5d93a84822a24f035

How do we want to style these? As is, borders, background colors etc.

**Comment by jlooper** [comment]
Regarding the very first issue Rob mentions, do we need to have such redundant information? For example this one is essentially duplicated title and "about" content:

https://www.dropbox.com/s/ly29f4gc3hgyzhs/Screenshot%202017-01-22%2012.49.32.png?dl=0

**Comment by georgeedwards** [comment]
@jlooper I completely agree. This was just following the original wireframes. Only issue is - do we want to completely rely on the author to format the info as we would like? If someone wants to make a decision, give me a shout and I'll change it.

**Comment by NathanWalker** [comment]
@georgeedwards I took care of redundant info and also have a method to cleanup any sanitized html from showdown, see this as an example of how I fixed the broken images from readme's:
https://github.com/NativeScript/plugins/blob/master/src/client/app/components/plugin/plugin.component.ts#L42

Similar method can be applied to anything that we can reasonably know what it *should* be. 👍
