### ISSUE TITLE
Improve responsive nature of plugin detail

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/plugins#43]
![image](https://cloud.githubusercontent.com/assets/1918280/22074788/2b6765e6-dd6f-11e6-96b0-38d558e19b8b.png)

- Make sure we are using whitespace available on left when needed
- Drop the sidebar to the bottom of the page instead of overlapping content text with sidebar

**Comment by georgeedwards** [comment]
Done. I haven't yet implemented the full mobile layout for the detail page as Nina specified, but it doesn't break now.
