### ISSUE TITLE
@nativescript/fingerprint-auth Support faceId for android

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/plugins#44]

**Comment by 3rror404** [comment]
Are there any plans to update this plugin? I've just wasted a substantial amount of time incorporating this plugin in to my app before realising that it does not work on Android 10+

**Comment by jcassidyav** [comment]
Supported via the [Biometrics](https://github.com/NativeScript/plugins/tree/main/packages/biometrics) plugin,
@nativescript/fingerprint-auth is depreciated.
