### ISSUE TITLE
Stripe support

### ISSUE THREAD

**Issue by careeat** [NativeScript/plugins#45]
I really like nativescript for cross-platform mobile app development.
But I realize that I spend a lot of time looking for plugins and that the community doesn't always provide the must-have plugins compared to others SDK like Flutter or React-Native. Is there a plugin for the integration of stripe for payment. Especially for Nativescript 7
Thank you in advance

**Comment by NathanaelA** [comment]
Please use https://plugins.nativescript.rocks it should tell you if a plugin exists.    If not their are many developers would would be willing to do contract work to build you a plugin...

**Comment by asharghi** [comment]
If you Google NativeScript Stripe, it's the first result. The team is working on NS7 support https://github.com/triniwiz/nativescript-stripe
