### ISSUE TITLE
Footer? Copyright?

### ISSUE THREAD

**Issue by jlooper** [NativeScript/plugins#45]
Don't we need a footer with copyright somewhere? @sipacate 👈 #

**Comment by jlooper** [comment]
from the NativeScript.org website, I think we ought to have this at the footer to match:

NativeScript is licensed under the Apache 2.0 license.  © 2017 Progress Software Corporation. All Rights Reserved.

**Comment by georgeedwards** [comment]
Done - https://github.com/NativeScript/plugins/commit/eb26d35009bf9362c9f540f62b30116a20c676d8
