### ISSUE TITLE
[@nativescript/localize] In iOS, error thrown for `null` value

### ISSUE THREAD

**Issue by meeshkabob** [NativeScript/plugins#46]
Currently in iOS, if `null` is passed to the `localize` method or to the localize pipe `| L`, an error is thrown:
`TypeError: Cannot read property 'match' of null`

Could the method and pipe be changed to match match the behavior in android, which is to return an empty string? This would be more in keeping with the library's otherwise more lenient edge case handling. 

```
localize("unknown key");  // returns "unknown key"
localize("");  // returns ""
localize(null);  // throws error in iOS, returns "" in android
```

Dependencies:
```
"@nativescript/localize": "^5.0.2",
"@nativescript/angular": "~11.0.0",
"@nativescript/core": "~7.0.0",
```

Devices:
* iPhone 12 Pro iOS 14.2 simulator
* Pixel 3 Android API 29 emulator

**Comment by NathanWalker** [comment]
Completely agree, thanks for tracking.
