### ISSUE TITLE
Don't pick image

### ISSUE THREAD

**Issue by Salmankhan033** [NativeScript/plugins#464]
When I try to get an image in IOS Simulator then it returns an empty object.
How to get images from storage?
I am using react hooks 
**Versions:**
```
   "react": "^16.14.0",
    "react-nativescript": "^4.0.0",
  "@nativescript/core": "~8.4.0",
    "@nativescript/imagepicker": "^1.0.9",
```

**Code:**
<img width="488" alt="Screenshot 2023-03-15 at 5 49 32 PM" src="https://user-images.githubusercontent.com/58082294/225313648-a972d6dd-56bd-4ca8-ba7a-e968d7587976.png">

**OUTPUT:**
<img width="197" alt="Screenshot 2023-03-15 at 5 50 18 PM" src="https://user-images.githubusercontent.com/58082294/225313801-287164ac-cf7e-4bab-ab38-181ad3b43713.png">

**Comment by rigor789** [comment]
The output looks correct to me - returns an array of `ImageAsset`s - in your logs you are logging out an ImageAsset (doesn't say in the console, but looks like it):
```
selected... {
"observers": {}
...
"keepAspectRatio": true
...
}
```
^ that's an ImageAsset instance

Depending on what you want to do with the image... For example you can display it in your app:

```
<Image src={selected} ...
```

should display the image

ImageAsset API: https://docs.nativescript.org/api-reference/classes/imageasset

**Comment by davecoffin** [comment]
As of 2.0 it would be `selected.asset`. See docs for 2.0 updates.
