### ISSUE TITLE
Replacing static "loading..." with gif...?

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/plugins#47]
I'd propose we drop the default "loading..." text with something more dynamic like a loading gif:

![rolling](https://cloud.githubusercontent.com/assets/1918280/22082627/247ca358-dd8e-11e6-9857-2122a7a5222e.gif)

**Comment by georgeedwards** [comment]
Done - https://github.com/NativeScript/plugins/commit/a0e3a508a10dfb05e9783f07b72cd1a618dd7067
