### ISSUE TITLE
GoogleMaps requires higher minimum deployment target for iOS

### ISSUE THREAD

**Issue by ubaidazad** [NativeScript/plugins#473]
Error with google-maps on ios

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/11173794/228020466-54aed155-557b-4cbf-93b0-478fe77a40b8.png">

added 
`IPHONEOS_DEPLOYMENT_TARGET = 9.0; `
in build.xconfig but still same error

**Comment by triniwiz** [comment]
The min for GoogleMaps v6 is iOS 12
