### ISSUE TITLE
DatePicker error when created

### ISSUE THREAD

**Issue by lpetic** [NativeScript/plugins#48]
I have this issue, but it's not critical. The DatePicker is displayed and works at the first look.

I'm using Angular and I share code between mobile and web verions.

> Error: node_modules/@nativescript/datetimepicker/angular/index.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

> This likely means that the library (@nativescript/datetimepicker/angular) which declares NativeScriptDateTimePickerModule
has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is
available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

> 3 export declare class NativeScriptDateTimePickerModule {

**Comment by NathanWalker** [comment]
Resolved with Angular 11, ensure using @nativescript/angular ~11.0.0
