### ISSUE TITLE
Lol, I see a comment flash when I switch page

### ISSUE THREAD

**Issue by jlooper** [NativeScript/plugins#48]
When I switch from home to a card I see a little comment to George flash on the screen, lol we ought to just use that loading image Rob recommended:

It's from here:

https://github.com/NativeScript/plugins/blob/3180ac011874ece231c25658e488fac5ff37aa10/src/client/app/components/plugin/plugin.component.html#L39-L41

**Comment by georgeedwards** [comment]
Yep - WIP tracked in #47
