### ISSUE TITLE
[@nativescript/google-maps] myLocationButtonTap event wrong type

### ISSUE THREAD

**Issue by Semurak** [NativeScript/plugins#482]
The event listener:

`on(event: 'myLocationButtonTap', callback: (args: MarkerTapEvent) => void, thisArg?: any);`

does not return a marker property in its callback, which is needed for MarkerTapEvent

**Comment by triniwiz** [comment]
This is [fixed](https://github.com/NativeScript/plugins/commit/07f3ca2f1917934c7dd09067a2eb6ac0956b71c0) in the latest release. Thank you
