### ISSUE TITLE
Add right padding to header

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/plugins#49]
Header links and search bar run right into the scroll bar. Just throw a little padding on there por favor:

![image](https://cloud.githubusercontent.com/assets/1918280/22250398/555edd7e-e20c-11e6-85c6-81825b895b1e.png)

**Comment by georgeedwards** [comment]
Done - https://github.com/NativeScript/plugins/commit/1115bc406fb4c53152c8f903491369c536ab939c
