### ISSUE TITLE
Not able to build the global demo app for Android and iOS

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/plugins#51]
Hello,

right now I am not able to build the demo app in this repository, I get the following error message while preparing the project:
> Preparing project...
> Multiple errors were thrown:
> Cannot find module '@nativescript/localize/hooks/before-watchPatterns.js'
> Require stack:
> - /Users/felixkrautschuk/PhpstormProjects/Forks/NativeScriptPlugins/apps/demo/hooks/before-watchPatterns/nativescript-localize.js
> - /usr/local/lib/node_modules/nativescript/lib/common/services/hooks-service.js
> - /usr/local/lib/node_modules/nativescript/lib/common/yok.js
> - /usr/local/lib/node_modules/nativescript/lib/bootstrap.js
> - /usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js
> - /usr/local/lib/node_modules/nativescript/bin/tns
> Cannot find module '@nativescript/localize/hooks/before-watchPatterns.js'
> Require stack:
> - /Users/felixkrautschuk/PhpstormProjects/Forks/NativeScriptPlugins/apps/demo/hooks/before-watchPatterns/nativescript-localize.js
> - /usr/local/lib/node_modules/nativescript/lib/common/services/hooks-service.js
> - /usr/local/lib/node_modules/nativescript/lib/common/yok.js
> - /usr/local/lib/node_modules/nativescript/lib/bootstrap.js
> - /usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js
> - /usr/local/lib/node_modules/nativescript/bin/tns
>

**Comment by janoshrubos** [comment]
Please ensure all plugins build properly first.

Run `npm start`
type "build-all" (and hit ENTER) or select the `@nativescript.build-all` option.
