### ISSUE TITLE
Feature: Picker in modal or dialog

### ISSUE THREAD

**Issue by sivo1981** [NativeScript/plugins#52]
Is it possible to create a plugin to show picker in modal or dialog the same as is already for date 

[https://github.com/NativeScript/plugins/blob/master/packages/datetimepicker/README.md](url)

**Comment by mykone** [comment]
> Is it possible to create a plugin to show picker in modal or dialog the same as is already for date 
> 
> 
> 
> [https://github.com/NativeScript/plugins/blob/master/packages/datetimepicker/README.md](url)

Would be nice for a plugin, but I recommend building your own. I had to do that to solve this issue. I built a reusable Vue plugin as a modal list-picker with autocomplete feature.

**Comment by sivo1981** [comment]
@mykone Thanks for the tip.

**Comment by sivo1981** [comment]
> @mykone Thanks for the tip.

@mykone Maybe you have some code to share?

**Comment by mykone** [comment]
> > @mykone Thanks for the tip.
> 
> 
> 
> @mykone Maybe you have some code to share?

Sure. I can give you a help.
