### ISSUE TITLE
@nativescript/camera problem with meta-data provider

### ISSUE THREAD

**Issue by omurtsckr** [NativeScript/plugins#53]
Hi.
I installed this plugin. when im tring to take picture, getting this error;

Error -> java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority org.nativescript.xxx.provider

How can i add provider ? There is no provider tag in my manifest.xml

please help

**Comment by omurtsckr** [comment]
This is my tns doctor result;

√ Getting environment information

No issues were detected.
√ Your ANDROID_HOME environment variable is set and points to correct directory.
√ Your adb from the Android SDK is correctly installed.
√ The Android SDK is installed.
√ A compatible Android SDK for compilation is found.
√ Javac is installed and is configured properly.
√ The Java Development Kit (JDK) is installed and is configured properly.
√ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
√ Getting NativeScript components versions information...
‼ Update available for component nativescript. Your current version is 7.0.10 and the latest available version is 7.0.11.
‼ Update available for component @nativescript/core. Your current version is 7.0.11 and the latest available version is 7.0.13.
× Component @nativescript/ios is not installed.
‼ Update available for component @nativescript/android. Your current version is 7.0.0 and the latest available version is 7.0.1.

**Comment by omurtsckr** [comment]
its ok after update nativescript.

**Comment by dukewan** [comment]
I ran into the same issue, how did you solve it? @omurtsckr

**Comment by omurtsckr** [comment]
Update nativescript and core. Run tns doctor and update all . Then you can
find current versions of plugins on nativescript rocks.

7 Şub 2021 Paz, saat 03:58 tarihinde Yizhao He <notifications@github.com>
şunu yazdı:
