### ISSUE TITLE
Remove border from code when inside pre tag

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/plugins#53]
We don't need the border on code samples when they are in a multi-line pre tag:

![image](https://cloud.githubusercontent.com/assets/1918280/22252146/e4314b94-e212-11e6-9894-0fd39b4d934f.png)

...should be:

![image](https://cloud.githubusercontent.com/assets/1918280/22252198/010e0c52-e213-11e6-8141-5f41003995a2.png)

**Comment by georgeedwards** [comment]
@rdlauer Awesome eye sight :) 
This is now done - https://github.com/NativeScript/plugins/commit/ea423493b43f60d63f273837a0d417ca53d0033e
