### ISSUE TITLE
Last Published text in the plugin details right pane is incorrect

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/plugins#56]
From the plugin site:
![image](https://cloud.githubusercontent.com/assets/9464097/22464363/1cbca89e-e7bf-11e6-8290-871602aaf094.png)

From NPM:
![image](https://cloud.githubusercontent.com/assets/9464097/22464375/2d9458ba-e7bf-11e6-937a-4b155b3c36fc.png)

**Comment by NathanaelA** [comment]
I'm not seeing the difference; can you point out what I'm overlooking?

**Comment by PeterStaev** [comment]
Peter Staev published **a month ago**. 

vs

pstaev published **19 hours ago**

**Comment by NathanaelA** [comment]
@PeterStaev - should be fixed.  Thanks for the report!

![image](https://cloud.githubusercontent.com/assets/850871/22768273/857384ec-ee46-11e6-93e5-8ddf2c401749.png)
