### ISSUE TITLE
The plugin does not work with the new version of nativescript-vue

### ISSUE THREAD

**Issue by suprith-s-reddy** [NativeScript/plugins#57]
The dependecies are as follows:

   "@nativescript/core": "^7.0.3",
    "@nativescript/localize": "^5.0.2",
    "@nativescript/theme": "^2.3.3",
    "@panter/vue-i18next": "^0.15.2",
    "@vue/devtools": "^5.3.3",
    "nativescript-socketio": "^3.3.1",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-vue": "^2.8.1",
    "nativescript-vue-devtools": "^1.4.0",
    "vuex": "^3.5.1"

Followed steps as per documentation.

-  tns add plugin @nativescript/localize 

-  Then added in main.js - 

    import {localize} from '@nativescript/localize'
    Vue.filter('L', localize)

- Then in the vue template 
    <TabViewItem :title="'home' | L">

Used that, with en.default.json & de.json format file. Nothing changes nor works. I tried rebuilding the app as well. Does someone have a fix for this? Or have I missed out importing something? How does the plugin pick the json files? Should I import them somewhere??

A little help on this would be really appreciated. Also I could help if something is missing in the documentation. Its really hard to figure out without the documentation to be perfect.

**Comment by suprith-s-reddy** [comment]
It works, the issue was my setup.

**Comment by MarkOdey** [comment]
Could you provide more details on the steps taken to make it work. I am struggling to get it working through following the readme.
