### ISSUE TITLE
Search doesn't work on mobile

### ISSUE THREAD

**Issue by jlooper** [NativeScript/plugins#57]
You can type in the search box but no drop down appears

**Comment by bradmartin** [comment]
@jlooper - this is working for me on Chrome and in dev tools testing the different device layouts. If memory serves you're an iOS gal :) so I'm guessing Safari and I'm not on a Mac to test anything there.

**Comment by jlooper** [comment]
Ah! I just tested and this time it worked! I use Chrome on iOS
