### ISSUE TITLE
iOS @nativescript/social-share Error: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

### ISSUE THREAD

**Issue by maxlam79** [NativeScript/plugins#58]
Hi,

I'm getting this message when invoking SocialShare.shareUrl(someUrl, someTitle);

```
Error: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]
```

The share sheet didn't display. I've discovered this on iOS, yet to confirm on Android.

Platform: Nativescript 7.0.12 (Angular)
Mobile OS: iOS 14.3 (Emulator)
XCode version: 12.3
@nativescript/social-share version: 2.0.1

I have imported the library:
```
import * as SocialShare from '@nativescript/social-share';
```

Help needed. Thank you.

**Comment by danyadanch** [comment]
Hi! Please show me the code. But I can assume that you are giving the wrong url as the first argument for this function.

**Comment by maxlam79** [comment]
The URL constitutes of UTF-8 characters.

Anyway, here's a snippet of the code:
```
import * as SocialShare from '@nativescript/social-share';

// ... Usual angular class declaration here ... and follow by ...

testShare( ) {
        let shareUrl = 'https://christlifeliving.net/zh/sermons/仰望基督耶稣-常住在祂的爱里';
        let shareTitle = '仰望基督耶稣-常住在祂的爱里';
        SocialShare.shareUrl( shareUrl, shareTitle, shareTitle );
}
```
The URL is a valid one if it is called from browser (using Chrome/Safari in my case).

Hope this helps.

**Comment by NathanWalker** [comment]
I wonder if it's the characters in the that url, may need a certain encoding when passed to the args?
Confirmed shareUrl works fine, so can only think perhaps it's the character encoding.

**Comment by maxlam79** [comment]
Thanks for the pointers. Yes you are right, I have to use encodeURIComponent(...) on this.
