### ISSUE TITLE
NativeScript Social Share not listed on main page

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/plugins#58]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Visit <http://plugins.nativescript.org/> and scroll to the bottom so all plugins are present. Search for “social” with your web browser.

I expect the “nativescript-social-share” plugin to appear on the home page; it is not.

**Expected behavior**

I expect to see the “nativescript-social-share” plugin listed on the home page. Currently I can only find it through a search.

**What is the motivation / use case for changing the behavior?**

Not sure if this is a problem with the site or with my social share plugin.

**Please tell us about your environment:**

macOS, Chrome

**Comment by georgeedwards** [comment]
@tjvantoll Have you made sure you scrolled to the end of all the infinite scrolling? If it is in the search then it should be on the main page.

**Comment by tjvantoll** [comment]
@georgeedwards Hey. Yes, I see “Viewing 437 of 437 Plugins” but I don’t see the social share plugin.

**Comment by georgeedwards** [comment]
How weird - @NathanaelA @NathanWalker any ideas?

**Comment by NathanaelA** [comment]
Yep, fixed.   Silly me, the sorting was causing the issues...

**Comment by tjvantoll** [comment]
Thanks @NathanaelA for the super quick turnaround. I see social share now 😄 

One minor note: I noticed that the plugin detail pages do not show the start rating. That’s what made me start looking for the social share plugin on the home page in the first place. Not sure if that’s intentional or not but I thought I’d mention it.
