### ISSUE TITLE
AnimatedCircle plugin is not changing textSize

### ISSUE THREAD

**Issue by LMS5413** [NativeScript/plugins#583]
Hello. I'm using the AnimatedCircle plugin in AngularJS, but I noticed that the properties textSize and textColor don't work. However, I managed to change the textColor through CSS, and when I try to change the textSize through CSS, the text simply disappears, no matter what value I put.

## No text-size
![image](https://github.com/NativeScript/plugins/assets/58144443/baec807c-ec2c-4ba3-afb8-76cdd3cbf4f8)

## With text-size 

![image](https://github.com/NativeScript/plugins/assets/58144443/136ca2bb-2315-4fd0-9101-ded5a95a2e9e)

**Comment by vallemar** [comment]
@LMS5413 fixed in https://github.com/NativeScript/plugins/pull/584
@NathanWalker you can have a look?

**Comment by LMS5413** [comment]
Its Worked!
