### ISSUE TITLE
Package nativescript-permissions is deprecated

### ISSUE THREAD

**Issue by liuy97** [NativeScript/plugins#589]
The detail is https://www.npmjs.com/package/nativescript-permissions
```
This package has been deprecated

Author message:

Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
```

This package is still used in @nativescript/camera, @nativescript/geolocation and @nativescript/contacts. @nativescript-community/perms can be used instead.

**Comment by jcassidyav** [comment]
This has been resolved in the latest versions of @nativescript/camera, @nativescript/geolocation and @nativescript/contacts by #594
