### ISSUE TITLE
Might need to change install wording

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/plugins#59]
![tnsplugin](https://cloud.githubusercontent.com/assets/6006148/22520510/2b8f61a2-e87a-11e6-9e80-485a52f3a227.PNG)

I don't know the specifics of the internals of the `tns plugin` command but I am fairly confident that running `npm install` vs. `tns plugin add` causes issues. I've had a couple issues on plugin repos and it was fixed by running `tns plugin` when they ran `npm install`. I've tried changing the README on all plugins to read `tns plugin add` also due to people opening issues after only doing `npm install`

Maybe someone on the CLI team can clarify any differences or @NathanaelA might know. I've never looked at the CLI code 😄

**Comment by NathanaelA** [comment]
@bradmartin Thanks for bringing it up.  I saw that the other day and meant to report it myself.  ;-)

We do need this to say `tns plugin add` for all plugins EXCEPT developer plugins that start with `nativescript-dev-YYY` plugins should be `tns install YYY`  (no `nativescript-dev-` in the install command)
