### ISSUE TITLE
User Logging in

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/plugins#6]
We have to have our own database for sure for user rankings, ip tracking and stats for certain things

The actual logging in part we could 

1. Link to popular services like Google, Facebook, Twitter, Github?
2. Just maintain our own database.

**Comment by georgeedwards** [comment]
In my proposal, I used Auth0 (free for open-source profits). Which allows us to use any of the services you proposed (and loads of others in the future). I think that's much simpler than haveing our own database. If you click the "add" button on [my proposal](https://ns-docs.herokuapp.com/plugins), you'll see how it works. My source code shows it integrating with ng2 and using it to secure a backend API (express based)

**Comment by NathanaelA** [comment]
I don't have an issue using Auth0.  That is why I brought up the question to make sure everyone was thinking the same thing.  ;-)       To be honest I'm not against having just our own either; I really don't care either way.  ;-)   

We do need some place to store user rankings, review text, ip's, etc, which is why I believe we need to have a db of some sort.

**Comment by georgeedwards** [comment]
Yep, I agree. I like having Auth0 because that way we don't have any particularly sensitive data in our db. But don't feel massively strongly either way.

**Comment by NathanWalker** [comment]
Auth0 it is! I really like that option as well. We will plan to integrate that into the setup. 👍

**Comment by NathanWalker** [comment]
@jlooper when you get a chance, could you register an account for us to use with Auth0 and just sign us up for the Free plan (which should hold this for quite awhile):
https://auth0.com/pricing

**Comment by jlooper** [comment]
ok, I have created the account (I love Auth0 as well)

progress.auth0.com

I'll email the authentication info

**Comment by NathanWalker** [comment]
Hooray! Thanks @jlooper !

**Comment by NathanaelA** [comment]
Ok, I think this issue is settled.  Auth0 it is.  That was easy...  Lets hope the rest go as smoothly...  ;-)
