### ISSUE TITLE
@nativescript/localize did not have support @nativescript-dev/multiple-environments

### ISSUE THREAD

**Issue by jitendraP-ashutec** [NativeScript/plugins#61]
Nativescript/localize has not support if we create different localize file for different environments as @nativescript-dev/multiple-environments suggested. Android copy all environment's localize files and it is creating issue in compiling.

**Comment by jitendraP-ashutec** [comment]
Hi @NathanWalker  @NathanaelA 

I have changed code to support @nativescript-dev/multiple-environments in @nativescript/localize.
I have created PR could you please review and merge it so it will help other user also.
PR: https://github.com/NativeScript/plugins/pull/62

Let me know if you want any changes in PR.

Thanks,
Jitendra Prajapati

**Comment by NathanWalker** [comment]
Thank you @jitendraP-ashutec pr merged and released with 5.0.3
