### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by jlooper** [NativeScript/plugins#61]
http://plugins.nativescript.org/plugin/nativescript-plugin-firebase

This page is an example of missing images - the firebase logo at the top appears to reference a relative path. Why do some images display and others not? I'm guessing it is some sort of path issue.

**Comment by bradmartin** [comment]
![no](https://cloud.githubusercontent.com/assets/6006148/22721754/376004b6-ed78-11e6-9301-6c01403e9a4d.PNG)
![yes](https://cloud.githubusercontent.com/assets/6006148/22721753/375f1d9e-ed78-11e6-8e74-5b6e7ab16ac6.PNG)

for more context on the path issue in the source

**Comment by bradmartin** [comment]
Currently expecting images to be inside `screenshots` folder https://github.com/NativeScript/plugins/blob/master/src/client/app/components/plugin/plugin.component.ts#L53

**Comment by NathanWalker** [comment]
I'll add some more conditions to make these work 👍

**Comment by NathanWalker** [comment]
Fixed up 99% of cases - lemme know if you find any others 👍
