### ISSUE TITLE
@nativescript/camera does not properly support Android 11

### ISSUE THREAD

**Issue by AnthonyLenglet** [NativeScript/plugins#66]
the camera plugin required `requestLegacyExternalStorage` to be enabled in order to work in android 10, but this option is no longer available in Android 11, now we have to use `preserveLegacyExternalStorage `

However looking at the doc for this: https://developer.android.com/reference/android/R.attr#preserveLegacyExternalStorage
We can see that this won't always be taken into account
```
Note that this may not always be respected due to policy or backwards compatibility reasons.
```
This part seemingly affect simulators on Android 11

So as it stands it looks like the plugin has to support the new external storage to work reliably on Android 11, and I'm not sure this option will stay for Android 12

**Comment by NathanWalker** [comment]
Thank you @AnthonyLenglet for reporting this 👍

**Comment by NathanWalker** [comment]
Closed via https://github.com/NativeScript/plugins/pull/67

**Comment by NathanWalker** [comment]
Published support with 5.0.3

**Comment by AnthonyLenglet** [comment]
Test it on my end on android 10 and 11

On Android 10 (API 29), the app fully crashes the moment I take a picture, and I get this error when I take a picture
```
System.err: Failure delivering result ResultInfo{who=null, request=3453, result=-1, data=Intent {  }} to activity {com.app.name/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onActivityResult failed
System.err: Error: Cannot convert number to Ljava/lang/Integer; at index 1
```

On android 11 (API 30), I can't get the camera to open
however, if I set `targetSdkVersion 28` in app.gradle, the camera opens, but freezes when a picture is taken, and gives the same error as the one above
<img src="https://user-images.githubusercontent.com/36004334/105687729-16f5b080-5ef9-11eb-829a-8fbc62188a71.png" width="200"/>

Tested both with preserveLegacyExternalStorage, didn't see any difference

**Comment by jcassidyav** [comment]
I am seeing the same issue, 

Changing
``values.put(android.provider.MediaStore.MediaColumns.IS_PENDING, 1 as any);``
to 
``values.put(android.provider.MediaStore.MediaColumns.IS_PENDING, new java.lang.Integer("1"));``

and

``values.put((android as any).provider.MediaStore.Video.Media.IS_PENDING, 0 as any);``
to 
``values.put((android as any).provider.MediaStore.Video.Media.IS_PENDING, new java.lang.Integer("0"));``

Appears to fix it for me, at least the demo runs.

**Comment by NathanWalker** [comment]
https://github.com/NativeScript/plugins/commit/982719bcc707329aab7fbc0cf2f4a7960f1548c4
Thanks @jcassidyav Osei's fix went in based on your suggestion and it's published with 5.0.4 of camera now.

**Comment by jcassidyav** [comment]
Unfortunately I messed up and forgot a bit in my comments, ( I guess I should figure out what I need to do to raise a pull request properly) so the latest still raises an error.

anyway a further change is required:

``Utils.android.getApplicationContext().contentResolver.update(uri, values, null, null);``
to
``Utils.android.getApplicationContext().getContentResolver().update(uri, values, null, null);``

Additionally if the intent is that this work with apps that set the targetSDK to API 30 it appears that 

``
	<queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
    </queries>
`` 

is required in the AndroidManifest.xml file, I didn't notice the demo app is set to SDK 29 so didn't spot this.
This is what is causing the camera to not show in API 30 apps as 
``
if (takePictureIntent.resolveActivity(Utils.android.getApplicationContext().getPackageManager()) != null) {
``
is false

**Comment by triniwiz** [comment]
@jcassidyav that contentResolver name was the result for porting some kotlin code 🙈  forgot to change it also everything is finally fixed for 11+

**Comment by brysem** [comment]
> [982719b](https://github.com/NativeScript/plugins/commit/982719bcc707329aab7fbc0cf2f4a7960f1548c4)
> Thanks @jcassidyav Osei's fix went in based on your suggestion and it's published with 5.0.4 of camera now.

Thanks for the fix @NathanaelA. I can confirm it's working for Android but the latest version has broken things for iOS. Please see https://github.com/NativeScript/plugins/issues/72

**Comment by jcassidyav** [comment]
@triniwiz that's great, on the manifest changes, is that something that should go in the plugin 
AndroidManifest or leave it to the app developer to add if they are targeting api 30 ?

**Comment by gowthamansubramani** [comment]
The open camera intent is not working in android 11, but the same code is tested and working in Android 10
