### ISSUE TITLE
[@nativescript/local-notifications] Custom interval not working on iOS - incomplete feature

### ISSUE THREAD

**Issue by damianocorrado** [NativeScript/plugins#73]
Hi,
after updating plugin to version 5.1.0, which introduce the capacity of set a custom number interval (in days) when notification is scheduled, I noticed that custom intervals not works on iOS.
For example when I set a notification to schedule every X days (it works nice if scheduled daily).

In the iOS implementation of the plugin, call to method NSCalendar.**componentsFromDate** should be called with a **CalendarUnit** object and **date** object according to [apple reference](https://developer.apple.com/documentation/foundation/nscalendar/1414841-components?language=objc
) but CalendarUnit can only represent a specific range unit such minute, hour, day, month, etc. so currently is impossible to schedule a notification that triggers, for example, every 2 days and when this value is passed it introduces the insertion of a badly scheduled notification.

Example
```
LocalNotifications.schedule([
	{
		title: 'The title',
		body: 'Recurs every minute until cancelled',
                ...
		interval: 2,
		at: new Date(new Date().getTime() + 10 * 1000), // 10 seconds from now
	},
]).then(...)
```

Tested with
@nativescript/ios: "7.0.0"
@nativescript/core: "7.0.9"
nativescript-cli version 7.1.2

I hope this may help anyone, any suggestions are appreciated.
Thank you.

**Comment by insytes** [comment]
@NathanWalker I can pick this up

**Comment by NathanWalker** [comment]
That’d be awesome @insytes let us know if run into trouble.

**Comment by insytes** [comment]
> That’d be awesome @insytes let us know if run into trouble.

Thanks @NathanWalker. 

I have iOS working, looking at Android next.

There will be breaking changes included in the `ScheduleOptions.interval` option, which I think are unavoidable.

I am having trouble building & using the package locally, something you might be able to help with?

Each time I build the `local-notifications` package, `"type": "module"` is added to the `package.json` and I have to remove it manually? 🤷🏻‍♂️

**Comment by NathanWalker** [comment]
Great question @insytes yes, the workspace picks up ESM from tsconfig and adds those when doing a build alone, however when using `npm run publish-packages` it will strip those properties so you can use publish-packages which will build and then attempt to publish, which would fail due to auth token but your `dist/packages/local-notifications` would contain a proper build which you can `npm pack` and use. Give it a shot, sounds like great progress!

**Comment by insytes** [comment]
@NathanWalker, perfect, thanks 👍🏻
