### ISSUE TITLE
nativescript-picker missed in NS7 conversion to this repository

### ISSUE THREAD

**Issue by mcgouganp** [NativeScript/plugins#80]
nativescript-picker plugin appears to have been missed during NS7 migrations to this repository.

Confirmed by:
_@NathanaelA in https://github.com/NativeScript/nativescript-picker/issues/50#issuecomment-770067392_

**Comment by NathanWalker** [comment]
Hi @mcgouganp sure thing, it's updated and published now @nativescript/picker 3.0.0
