### ISSUE TITLE
[@nativescript/social-share] conflicts with nativescript-facebook

### ISSUE THREAD

**Issue by PhilippS93** [NativeScript/plugins#81]
Hi everyone,

the new version of @nativescript/social-share 2.0.2 has defined its one provider for `com.facebook.FacebookContentProvider` in the AndroidManifest.xml which conflicts with the definition of the provider which is necessary for [nativescript-facebook](https://github.com/NativeScript/nativescript-facebook) to work.

How can that be fixed and where do I need to specify the ApplicationID in AndroidManifest.xml?

Thanks in advance,

Philipp

**Comment by NathanWalker** [comment]
@PhilippS93 thanks for mentioning this - we're bumping a patch out shortly to remove the transient include and make it explicit if user wants to engage with the new functionality.

**Comment by NathanWalker** [comment]
Published in 2.0.3 now - anyone who experienced this, just `ns clean` and should be fine on next run/build.
