### ISSUE TITLE
@nativescript/camera plugin

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/plugins#84]
Hi,
Is there documentation for the @nativescript/camera plugin?
I would like to use the take photos as well as picking from the gallery. Plain JavaScript if possible.

Thanks,

**Comment by NathanWalker** [comment]
Thanks for reminder @alexisconsuegra you can find it here now:
https://github.com/NativeScript/plugins/tree/master/packages/camera#nativescript-camera

And we published a patch to npm to include the same.
