### ISSUE TITLE
Empty rejection

### ISSUE THREAD

**Issue by pfumagalli** [NativeScript/plugins#85]
Please see https://github.com/NativeScript/plugins/blob/ad90bd4b6d3e749b2d400c5e936b2a1b712665be/packages/imagepicker/index.ios.ts#L85

When dismissing the image picker on `iOS`, the promise is rejected, meaning that in an `async` function, it will throw an `undefined`. E.g.

```js
try {
  const assets = await picker.present()
  ...
} catch (error) {
  // here "error" can be "undefined"
}
```

May I suggest to re-code as follows?

```js
this._reject(new Error('Canceled'));
```

**Comment by NathanWalker** [comment]
Sure thing, good idea - published in `1.0.3` now 👍

**Comment by pfumagalli** [comment]
Thank you @NathanWalker ... For future references, should I submit a PR for little things like those together with / instead of a bug report?

**Comment by NathanaelA** [comment]
Yes, we love PR's.
