### ISSUE TITLE
[@nativescript/email] Android 11

### ISSUE THREAD

**Issue by JonasSkovLykke** [NativeScript/plugins#88]
Can't attach a file (pdf) to a mail, on an Android 11 device :/

**Comment by JonasLykkeIOspect** [comment]
@janoshrubos nice...
Just waiting for them to approve, merge and release :)
Have tried to manuelt use your code. But I did not have any success with it :(
Dont know how to install/use a plugin without adding it with "npm i"

Now im waiting for the share-file plugin to get updated to. I'll be able to send an pdf file via my email, with your fix :) But the share file plugin is broken. So have added an issue there also. the https://github.com/nativescript-community/ui-share-file does not support adding an issue. So I have tied elsewhere.

Anyways. TY for the help ;)
