### ISSUE TITLE
[@nativescript/email] Android 11 FileProvider

### ISSUE THREAD

**Issue by JonasLykkeIOspect** [NativeScript/plugins#93]
Hi. First of all, thanks for fixing the Android 11 problem. But its not "all done" yet :)

For it to work, you need to have a FileProvider in your AndroidManifest.

@NativeScript/camera comes with one. So if you're already using that one. Change line 160 in the index.android.js:

**From:**
_return FileProviderPackageName.FileProvider.getUriForFile(Application.android.context, Application.android.nativeApp.getPackageName() + **'.fileprovider'**, file);_

**To:**
_return FileProviderPackageName.FileProvider.getUriForFile(Application.android.context, Application.android.nativeApp.getPackageName() + **'.provider',** file);_

**'.provider'** is the FileProvider that @NativeScript/camera makes. So you can reuse that.

This is a fix, until the plugin is updated with a FileProvider :)

**Comment by rigor789** [comment]
Would you mind opening a PR with that change, so we can get it merged & released?

Long-term we probably want to extract common FileProvider handling to perhaps it's own plugin or even core if it makes sense to simplify the process!
